### ISSUE TITLE
What's the best way to add incumbent MPs who won a by-election?

### ISSUE THREAD

**Issue by lizconlan** [mysociety/yournextrepresentative#116]
Example - Dan Jarvis MP (Labour), Barnsley Central http://yournextmp.com/constituency/65665/barnsley-central

(I've already flagged the winner of the 2010 election as not standing again - he stood down in early 2011, shortly before his conviction for expenses fraud)

**Comment by mhl** [comment]
I think we know the answer to this now :) The by-election should be added as a separate election, and the person should be added as a candidate for that. DemocracyClub are trying to cover every election in the UK now, which includes by-elections. (How far back it would be worth adding historic by-elections is a separate question.)
