### ISSUE TITLE
Make the requests for users to help much more prominent and strongly worded

### ISSUE THREAD

**Issue by TomSteinberg** [mysociety/yournextrepresentative#138]
So how about:

"This database of General Election candidates is being built by people like you! Please take a few moments to add extra details about candidates and parties - it only takes a moment."

And also on the candidate pages the call to action is at the bottom, when it should be at the top.

**Comment by mhl** [comment]
We made such a change while the emphasis was on getting people to help with crowd-sourcing, and later the messaging changed to put the emphasis on finding out about candidates instead. This can be closed now.
