### ISSUE TITLE
make a list of things involved in making the codebase generic enough for reuse

### ISSUE THREAD

**Issue by mhl** [mysociety/yournextrepresentative#145]
For example, just to start with:

* Allow arbitrary elections to be added (at the moment two are hardcoded, but referred to consistently by the identifiers `"2010"` and `"2015"`)
* The `ConstituencyDetailView` has a lot of logic specific to the UK 2010 / 2015 general elections; it would be nice to make this more generic anyway, since it's pretty unreadable at the moment.
* Allow a particular boundary service (and data generation) to be configured to define constituencies - at the moment MapIt and the UK general election constituencies for 2010 and 2015 are assumed
* Make all the strings in the interface translatable.

Things like these are relatively straightforward, however, compared to, say:

* Extend the codebase to cope with different electoral systems, or at least decide on which electoral systems we're going to support. (There are lots of assumptions about this embedded in the design.)

**Comment by mhl** [comment]
This issue was created in response to the discussion on the Poplus list here:

* https://groups.google.com/forum/#!topic/poplus/wZcQM508l4c

**Comment by mhl** [comment]
Another thing that I would want to do:

* Probably get rid of the flattened / simplified JSON representation used for versioning and just store the complete person record, including memberships, in the versions array; the mapping between representations has turned out to cause a variety of subtle problems.

**Comment by mhl** [comment]
Another one:

* YourNextMP currently assumes that there's a canonical list of registered political parties, which is scraped and imported. There's deliberately no support for users adding new parties any more, since it was almost always the case that they're creating a duplicate, and parties that aren't registered with the Electoral Commission aren't going to appear on the ballot anyway. However, in other electoral systems it might be necessary to have an interface to allow users to add parties.

**Comment by tmtmtmtm** [comment]
Slightly separately from reuse of the whole thing in other countries, YourNextMP the "Crowdsourced UI for editing a PopIt" elements are also potentially useful in other contexts as well. I could see EveryPolitician wanting to reuse a lot of this.

**Comment by mhl** [comment]
I don't think it's useful to keep this open any more - the most important points here have been dealt with.
