### ISSUE TITLE
(Auto) Upload Photos & Copyright?

### ISSUE THREAD

**Issue by edent** [mysociety/yournextrepresentative#148]
As an editor, I would like to directly upload - or link to - a candidate's profile photo.

Wondering about the copyright of such photos, I wonder if it would be possible to automatically grab the Twitter profile photo?

Using a service like Avatars.io it's as simple as http://avatars.io/twitter/edent (to get my Twitter avatar).

**Comment by tfgg** [comment]
For what it's worth, I snagged every candidate's Twitter profile pic when I made http://yournextmep.com and didn't get a single complaint. It was a very effective way of getting a photo for everyone, after a bit of automated cropping.

Obviously that doesn't mean the copyright/license problem is solved! On licensing I had significant issues explaining creative commons to people trying to email me photos and quickly gave up.

**Comment by andylolz** [comment]
I’m wondering about this, too. I just got loads ~400 CC-BY wikipedia images of candidates, and could easily add attributions to the sources. Presumably that’s sufficient for copyright purposes?

Auto-cropping might be tricky, though!

**Comment by edent** [comment]
Having been doing this by hand so far.

For example http://avatars.io/twitter/edent points to a 48px*48px image at http://pbs.twimg.com/profile_images/417381475101593601/UUi48hOg_normal.jpeg

Remove the `_normal` and you get the full sized http://pbs.twimg.com/profile_images/417381475101593601/UUi48hOg.jpeg

Still needs a manual review - not all the avatar images are mugshots, but an automated way could be handy.

**Comment by mhl** [comment]
There's a command for importing Twitter avatars for candidates into the moderation queue now: https://github.com/DemocracyClub/yournextrepresentative/blob/master/candidates/management/commands/candidates_add_twitter_images_to_queue.py - the plan of @symroe was to run this every night. I think the only thing stopping that at the moment is that it will requeue avatar photos that have already been moderated. I've created [an issue for that in the DC fork's issues](https://github.com/DemocracyClub/yournextrepresentative/issues/105), and I'll close this now.
