### ISSUE TITLE
plan out how we're going to update the site when the official lists are published

### ISSUE THREAD

**Issue by mhl** [mysociety/yournextrepresentative#175]
As soon as the official lists are published (10 days before the election, or whatever) we'll need to go through all 650 constituencies and update our lists based on the official lists. It'd be a good idea to have a plan in place for doing this, so we can get it done as quickly and accurately as possible.

**Comment by tfgg** [comment]
So the Statement of Nominations PDFs are put up on random council websites all over the place and are a bit of a faff to find. Edmund made a crowdsourcing tool for finding the PDFs and then another tool for checking the PDF against the known candidates and making any corrections. So the steps are

1. Find statement of nominations for every constituency
2. Check data against current data
3. Fix discrepancies
4. Mark candidacies as being properly nominated

One possibility that I'm keen to research is using a PDF table extraction service like pdftables.com to do the grunt work of pulling the data out. I did a test run on a PDF I had lying around from the 2014 EU Parliament election and it did a great job:

https://docs.google.com/spreadsheets/d/17902ba2d011nw3jvzwtTRt2XwczUtAKzkPfzAUl4xIE/edit?usp=sharing

Candidate data (and other goodies like postal addresses for matching to previous elections!) can then be easily pulled out. This data could then just be used verbatim to update the data, or be stuck into a crowdsourcing tool for resolving discrepencies.

So, my idea of a plan:

**Before nominations research**
1. Get all the 2010 PDFs and where they were found, these will have a lot of variance in them, different layouts, etc.
2. Try pdftables on them.
3. See how much variance in structure there is, whether it works for all the PDFs or not.
5. Write post processors to turn the extracted data into some sort of standard "statement of nominations" representation
6. Hope that councils haven't changed their format much.
7. Make a list of election subsites on councils that are likely to have the nominations posted to them
8. Make tools to associate PDFs with constituencies (automatically or manually) and to take a PDF/structured data and compare to existing data

**For nominations day**
1. Possibility: Scrape council election sites looking for changes and grabbing any posted PDFs and parsing
2. Volunteers to go PDF hunting and registering them with us
3. Volunteers to check data, either against structured data or raw PDFs.
