### ISSUE TITLE
Link URLs missing from persons API

### ISSUE THREAD

**Issue by sjorford** [mysociety/yournextrepresentative#195]
e.g. 
https://yournextmp.com/person/2279/claudia-beamish
http://yournextmp.popit.mysociety.org/api/v0.1/search/persons?q=name:%22Claudia%20Beamish%22

      "links": [
        {
          "id": "54d9e835346b683458afd698",
          "note": "wikipedia"
        }
      ],

The URLs are present as "wikipedia_url" etc. under versions, but not in the links element.

**Comment by mhl** [comment]
Thanks for reporting this, @sjorford. @chrismytton pointed out that the URL is present in the links array in  http://yournextmp.popit.mysociety.org/api/v0.1/persons/1151 which strongly suggest it's a problem with PopIt's ElasticSearch indexing; I'll create a PopIt issue, and we'll reindex soon (which presumably will fix this symptom if not the cause)...

**Comment by mhl** [comment]
Now we're no longer use PopIt for the data storage and API this is no longer relevant
