### ISSUE TITLE
external links on constituency pages aren't prominent enough

### ISSUE THREAD

**Issue by mhl** [mysociety/yournextrepresentative#232]
I strongly suspect that no one is clicking the ElectionLeaflets and MeetYourNextMP links on constituency pages because they're so far down the page, so it might be worth thinking about putting them "above the fold" perhaps as in the right-floated action boxes on the people pages.

**Comment by jarofgreen** [comment]
So far today Google Analytics reports 9 link thru, so not quite no-one - but I would never say no to more prominent linkage :-P

However I am aware that you lot have to make sure that real estate isn't to overloaded with messages, and I've got a lot of this message managing to do on my site, so I'll leave you to decide what should or shouldn't be promoted there.

But thanks for the thought :-)

**Comment by mhl** [comment]
I'm closing this because YNR is now just for crowd-sourcing - the presentation is done by [WCIVF](https://whocanivotefor.co.uk/)
