### ISSUE TITLE
the CSV download is sometimes broken by pagination

### ISSUE THREAD

**Issue by mhl** [mysociety/yournextrepresentative#284]
The CSV download is generated by going through the pages of:

* https://yournextmp.popit.mysociety.org/api/v0.1/persons/?embed=membership.organization&per_page=100

@frabcus found that one candidate appeared twice in the CSV file at one point, which must be because of it appearing in multiple pages. We should ensure that:

* Duplicate candidates aren't included
* Candidates aren't missed

Currently the ordering seems to be alphabetically on the ID; so they currently begin:
* `"1"`
* `"10"`
* `"100"`
* `"1001"`
* `"1002"`

If there was an option to sort on these treated as numbers (e.g. like `sort(1)`'s `-g` parameter) this would be easy to avoid, because when we create new candidates they've given an ID of max(ID) + 1, and never reuse earlier IDs.

@chrismytton Do you have a suggestion for this?

**Comment by dracos** [comment]
I guess the only sort order that would guarantee not potentially missing something (if someone's IDs were not sorted in alphabetic or numeric order, or weren't sortable at all) would be in database-creation order ascending (or e.g. descending if you had a `start_from` parameter rather than `page`)?

**Comment by mhl** [comment]
I'm going to close this as a "wontfix" since it won't be relevant after the switch away from PopIt.
