### ISSUE TITLE
City of Chester nomination paper url incorrect

### ISSUE THREAD

**Issue by scraperdragon** [mysociety/yournextrepresentative#316]
Document is for Ellesmere Port and Neston: url should be http://www.cheshirewestandchester.gov.uk/pdf/Statement%20of%20Persons%20Nominated_Parliamentary-coc.pdf

**Comment by scraperdragon** [comment]
ref: https://yournextmp.com/upload_document/130/

**Comment by andylolz** [comment]
Hi Dave,

If you are looking for stable URLs, I’m afraid the links to the statements of nominations are not it! Anecdotal evidence suggest lots have changed in just the last two days.

Out of interest: Are you looking to pull data out of these things? (If so, amazing!)

**Comment by andylolz** [comment]
Ahh – in fact… The document is correct – City of Chester starts on page 5. But I agree that the URL you give is preferable – I’ll update that now.
