### ISSUE TITLE
Merging candidates doesn't seem to preserve images correctly

### ISSUE THREAD

**Issue by tfgg** [mysociety/yournextrepresentative#318]
After merging this candidate

https://yournextmp.com/person/2042

his image field seemed to be copied across correctly, but it isn't showing up. The proxy_image field doesn't appear to be in the JSON?

http://yournextmp.popit.mysociety.org/api/v0.1/persons/2042

**Comment by andylolz** [comment]
I just made another edit, just to see what would happen. The image removal is shown as part of that diff.

**Comment by mhl** [comment]
@tfgg I suspect you could also have fixed this by clicking "invalidate cache" on the person page afterwards. I bet I forgot to automatically invalidate it after a merge...

**Comment by andylolz** [comment]
It doesn’t look like a problem of cache invalidation. The image on the primary profile (i.e. the one that’s being merged into) has been overwritten by that on the secondary. The secondary image here was `null`, and the primary was actually an image.

**Comment by symroe** [comment]
I've just merged [Amelia Womack](https://candidates.democracyclub.org.uk/person/7460/amelia-womack) and her image was not transferred to the new person ID either.
