### ISSUE TITLE
Merged candidates 404 instead of redirecting

### ISSUE THREAD

**Issue by andylolz** [mysociety/yournextrepresentative#375]
e.g.
https://edit.yournextmp.com/person/3402 was merged into
https://edit.yournextmp.com/person/7382
…but instead of redirecting (as was previously the case), 3402 now returns as not found.

**Comment by mhl** [comment]
Fixed - this works now: https://candidates.democracyclub.org.uk/person/3402 redirects

**Comment by andylolz** [comment]
https://edit.yournextmp.com/person/3402 -> https://candidates.democracyclub.org.uk/person/3402 (301) -> https://candidates.democracyclub.org.uk/person/7382 (301)

❤️
