### ISSUE TITLE
Styling for Argentina site

### ISSUE THREAD

**Issue by zarino** [mysociety/yournextrepresentative#395]
Make a theme for Argentina based on the YNMP theme, but with Congreso Interactivo’s colours.

It's likely that we'll have more themes like this in future. So, it'd be a good idea to make sure raw colour variables (eg: `$color-red`) aren't used in any of the core CSS declarations, and instead use generic variable names (eg: `background-color: $header-background-color;`) which cobrands can easily override.

Once this is done, it should be trivial to create a new theme which just inherits from the core theme but overrides the default colours.

**Comment by zarino** [comment]
Pull request with my work so far: https://github.com/mysociety/yournextmp-popit/pull/400

**Comment by mhl** [comment]
Just to add a small to-do, `icon-candidates.gif` doesn't work well as it stands due to having a white background:

![icon-candidates](https://cloud.githubusercontent.com/assets/7907/8253829/4d6b983a-168b-11e5-8aa8-af2c0af27e9e.png)

**Comment by JenMysoc** [comment]
Ok having spoken to Martin homepage needs to include;

Space for text about goal of the research and call to action to get data put in
Form to enter postcode or location (or to auto locate) - same as the UK one
Space for presentation - probably in powerpoint or google sheets - showing volunteers how to participate (This will be available from July 3rd 2015 - not currently finished)

The footer needs to have some space for 4 organisation logos and a list of collaborating orgs (to be provided)

**Comment by zarino** [comment]
@JenMysoc @martinszy is roughly what you're thinking of?

![homepage 1](https://cloud.githubusercontent.com/assets/739624/8430135/32e763ec-1f26-11e5-90ca-32c3b300ca53.png)

**Comment by martinszy** [comment]
That looks great.

**Comment by zarino** [comment]
@martinszy I've just pushed a change to [branch issues/395-homepage-styling](https://github.com/mysociety/yournextmp-popit/tree/issues/395-homepage-styling) that implements a layout like the wireframe above.

![screen shot 2015-06-30 at 16 52 34](https://cloud.githubusercontent.com/assets/739624/8435351/b6c52b8c-1f48-11e5-83ed-861c7fc0798b.png)

Let me know what you think.

**Comment by martinszy** [comment]
I like it, the "why not start with" should diplay the 5 posts that have less candidates.
I'm worried about the form with location search, I hope it works for any address.
We should also add a link to a list of provinces there ... or maybe the posts page.

**Comment by martinszy** [comment]
Also, a few ideas about the header:
1. logo is too big, maybe 20% smaller
2. can the logo be left-aligned?
3. the sign in/sign out buttons could be at the top?
4. we should add links to our social media sites:
@yoquiersaber in twitter 
and https://www.facebook.com/YoQuieroSaber

We are working the text for the page here:
https://docs.google.com/document/d/1NInK0-p79gsQzpyyHZlFKZ_yW7nvI-rgAn63jND9Q-g/edit

**Comment by JenMysoc** [comment]
@martinszy SHould the link to list of provinces go in the menu? That would be my initial thought.
Do you want the social media links as buttons or as a link saying "Twitter" "Facebook"

**Comment by zarino** [comment]
I would +1 having the provinces as a main item in the primary navigation.

Developer time permitting, we could *also* have them as a dropdown menu, like YourNextMP did in the UK:

![constituency](https://cloud.githubusercontent.com/assets/739624/8449678/8d30aa98-1fcb-11e5-80e0-aec8c7ee249e.gif)

**Comment by zarino** [comment]
Homepage pull request here: https://github.com/mysociety/yournextmp-popit/pull/414

**Comment by mhl** [comment]
@martinszy I've put this front page onto our staging site, including the draft translations from your document:

http://argentina.ynr.staging.mysociety.org/

The "which posts should you start with?" now shows a random selection of the posts with the lowest number of candidates. The address box should also work - it just adds ", Argentina" to the end of a string sent to Google's geocoder.

Your document suggests different translations for the menu bar items - should they take precedence over the translations in the .po files? If so, I'll replace them.

**Comment by martinszy** [comment]
I can change the .po files once the team agrees.
The box works nice in my tests.
The "add new candidate" button still doesn't work.

2015-07-01 13:58 GMT-03:00 Mark Longair <notifications@github.com>:

> @martinszy <https://github.com/martinszy> I've put this front page onto
> our staging site, including the draft translations from your document:
>
> http://argentina.ynr.staging.mysociety.org/
>
> The "which posts should you start with?" now shows a random selection of
> the posts with the lowest number of candidates. The address box should also
> work - it just adds ", Argentina" to the end of a string sent to Google's
> geocoder.
>
> Your document suggests different translations for the menu bar items -
> should they take precedence over the translations in the .po files? If so,
> I'll replace them.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mysociety/yournextmp-popit/issues/395#issuecomment-117751151>
> .
>



-- 
*Martín Szyszlican*
Desarrollo web usable y accesible
martinszyszlican.com

**Comment by mhl** [comment]
@martinszy Sorry, the fix for the "add new candidate button" hadn't been merged yet. That's done now on the staging site, so that should work for you.

I've merged @zarino's pull request, but I'll leave this ticket open until the logos are added.

**Comment by zarino** [comment]
More work towards fixing broken styles across the site: https://github.com/mysociety/yournextmp-popit/pull/420

The only thing left, as far as I'm aware, is the footer, for which we're currently awaiting partner logos.

**Comment by martinszy** [comment]
Partner logos are here, we're just missing the one from ACIJ:
https://drive.google.com/drive/u/0/folders/0Bz6IH4grpvxcfk5PQzVzUk5LQVJiZDRRLUtHTDk0bnp0LTdKbnhucE0teWlqamZEbldEcTA

And the order is here:
https://drive.google.com/open?id=1uS6mc0yfm85dZfJt5pwS_qjB55mcT7yeQ6np6c8CzUc

Martín.

2015-07-02 9:53 GMT-03:00 Zarino Zappia <notifications@github.com>:

> More work towards fixing broken styles across the site: #420
> <https://github.com/mysociety/yournextmp-popit/pull/420>
>
> The only thing left, as far as I'm aware, is the footer, for which we're
> currently awaiting partner logos.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mysociety/yournextmp-popit/issues/395#issuecomment-118022962>
> .
>



-- 
*Martín Szyszlican*
Desarrollo web usable y accesible
martinszyszlican.com

**Comment by JenMysoc** [comment]
Yamila has left this comment about the logos and the text for the footer:

3 logos [for the footer are] Interactive Congress, Open Knowledge and Data Concepcion Argentina
Listed as links are: Partner: Legislative Directory, Taringa, Association Consciousness and We-I
Support: HacksLabs
Development: mySociety, intelligent citizen [I'm guessing this is FCI] and Web Clinic (Martin)
All volunteers below
