### ISSUE TITLE
Extract UK-specific styles from core YourNextRepresentative stylesheets

### ISSUE THREAD

**Issue by zarino** [mysociety/yournextrepresentative#399]
Related to #395, which establishes a "cobrand" of YNMP for Argentina.

It looks like the core stylesheets at `/candidates/static/candidates/*.scss` contain a number of styles for things that aren't core functionality (like the layout and colouring of the homepage). Sometimes this requires cobrands to define variables for these styles to compile with, even though the styles won't _actually_ be used by the cobrand.

I think @mhl is working on extracting a lot of the functionality out of core and into a UK election-specific theme, just like the Argentinian one. Once this is done, we should remember to extract all the associated styles, so other cobrands don't have to worry about them or the variables they require.

**Comment by mhl** [comment]
We've done this now (mostly @zarino :))
