### ISSUE TITLE
Update the candidates for provincial representatives of Buenos Aires and minor posts

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/yournextrepresentative#438]
As per Martín's email:

"We have managed to scrape the list of candidates for provincial representatives of Buenos Aires, together with governors, mayors and other minor posts.

All this is available here in CSV format:
https://github.com/YoQuieroSaber/bascrap/blob/master/salida/

The issue with this is that the representatives are not from each department, but from "electoral sections" that are composed of several departments.

Here's the list of all electoral sections and the deapartments for each:
https://es.wikipedia.org/wiki/Secciones_electorales_de_la_Provincia_de_Buenos_Aires

And here you can see them in a clickable map in the site for the provincial senate:
http://www.senado-ba.gov.ar/inst_senadores_por_seccion_mapa.aspx

Can we accommodate this in MapIt and add it to YNR?"

Ideally before August 9th if possible.

**Comment by JenMysoc** [comment]
New file in .json format sent through. If you didn't receive it please ask me and I can send it over!

**Comment by martinszy** [comment]
Just to clarify.
The parties list was sent in JSON. National and provincial.

This issue is about the buenos aires municipal and department-level
candiates, which are available in CSV in the URL above.

Martín.


2015-07-16 6:58 GMT-03:00 Jen Bramley <notifications@github.com>:

> New file in .json format sent through. If you didn't receive it please ask
> me and I can send it over!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mysociety/yournextrepresentative/issues/438#issuecomment-121913478>
> .
>



-- 
*Martín Szyszlican*
Desarrollo web usable y accesible
martinszyszlican.com

**Comment by mhl** [comment]
@martinszy I've written [a MapIt command](https://github.com/mysociety/mapit/blob/argentina/mapit_ar/management/commands/mapit_AR_create_secciones_electorales.py) now to create the Secciones electorales out of the Department shapefiles from http://www.ign.gob.ar/NuestasActividades/sigign#descarga - this is mostly OK, **except** that those shapefiles are missing [Lezama](https://es.wikipedia.org/wiki/Partido_de_Lezama). Is it possible that you could find out from them if they have a shapefile for that department? (If you can't then I could always import [that boundary from OpenStreetMap](http://global.mapit.mysociety.org/area/689770.html) as a special case.)

As for importing the candidate information for the could you suggest what the new entry or entries in [the `ELECTIONS` data structure](https://github.com/mysociety/yournextrepresentative/blob/master/elections/ar_elections_2015/settings.py) should be for candidates competing at this level? (If it would be easier to go over this in a hangout, I'll be around all tomorrow - that might be helpful for me in interpreting what's in the CSV files.)

**Comment by mhl** [comment]
As discussed on a call with @martinszy the appropriate entry for the legisladores elections would be:

    # Legisladores
    'legisladores-provinciales-paso-2015': {
        'for_post_role': 'Legislador Provincial',
        'candidate_membership_role': 'Primary Candidate',
        'winner_membership_role': 'Candidate',
        'election_date': date(2015, 8, 9),
        'candidacy_start_date': date(2015, 6, 22),
        'organization_id': 'lprov',
        'organization_name': 'Legislaturas Provinciales',
        'name': 'Legisladores Provinciales PASO 2015',
        'current': True,
        'party_membership_start_date': date(2015, 6, 22),
        'party_membership_end_date': date(9999, 12, 31),
        'mapit_types': ['SEL', 'DPT'],
        'mapit_generation': 1,
        'post_id_format': 'legi-prov-{area_id}',
    },

**Comment by dracos** [comment]
The MapIt has the SEL areas in it now, plus manually copied Lezama.

**Comment by mhl** [comment]
I believe that we dealt with this, and the elections are over now, so I'm going to close this - I hope that's OK.
