### ISSUE TITLE
Make it easier to edit the "About" page

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/yournextrepresentative#443]

**Comment by martinszy** [comment]
We don't like this page's content, we're thinking of linking directly to the about page on the other site instead of this.
Otherwise we could just have an editor (maybe using django's flatpages and flatpages-ckeditor) so they are easily changeable.
We can discuss this.

**Comment by martinszy** [comment]
New page content: 

¡Bienvenido a Yo Quiero Saber, Investigación Colectiva! 

Conformamos una alianza apartidaria que lleva adelante el proyecto Yo Quiero Saber, que es una plataforma de Investigación Colectiva sobre los candidatos para las elecciones 2015. 

Junto a periodistas, politólogos, tecnólogos, organizaciones de la sociedad civil y voluntarios investigamos y recolectamos información de los candidatos del país para las elecciones primarias abiertas y simultáneas (PASO) del 9 de agosto y las presidenciales el 25 de octubre. 

Lo llamamos proyecto de investigación colectiva, porque creemos en el valor del trabajo entre la ciudadanía. 
Y necesitamos de tu ayuda para hacer crecer Yo Quiero Saber.

Sumate a nuestro grupo de colaboradores, vos también podés ser parte. Vamos a poner toda la información en el sitio web de Yo Quiero Saber, que fue desarrollado con software libre y la información publicada con licencias copyleft. 

Las organizaciones que hicieron posible este proyecto son: Congreso Interactivo, Open Knowledge Argentina, Fundación Directorio Legislativo, ACIJ, Asociación Conciencia, We-Me y Acción Social.

Con el apoyo de HackLabs, ICFJ, World Bank Institute, MySociety, Ciudadano Inteligente y Taringa.

**Comment by dracos** [comment]
This has been done; I have done it for simplicity for now as a separate override template in https://github.com/mysociety/yournextrepresentative/blob/master/elections/ar_elections_2015/templates/candidates/about.html .

**Comment by martinszy** [comment]
Thanks!

2015-07-23 15:00 GMT-03:00 M Somerville <notifications@github.com>:

> This has been done; I have done it for simplicity for now as a separate
> override template in
> https://github.com/mysociety/yournextrepresentative/blob/master/elections/ar_elections_2015/templates/candidates/about.html
> .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mysociety/yournextrepresentative/issues/443#issuecomment-124185896>
> .
>



-- 
*Martín Szyszlican*
Desarrollo web usable y accesible
martinszyszlican.com
