### ISSUE TITLE
Server error in staging

### ISSUE THREAD

**Issue by martinszy** [mysociety/yournextrepresentative#452]
This page shows an error:
http://argentina.ynr.staging.mysociety.org/numbers/election/gobernadores-argentina-paso-2015/parties

But this one doesnt: 
http://argentina.ynr.staging.mysociety.org/numbers/election/diputados-argentina-paso-2015/parties

**Comment by dracos** [comment]
Haven't fixed it, but for reference the issue is the URL generator for a party assumes the party organization ID is of the form `[a-z-]+:[-\d]+` when in this case it is just 'unknown'.
