### ISSUE TITLE
Changes in the header

### ISSUE THREAD

**Issue by martinszy** [mysociety/yournextrepresentative#454]
- [x] 1) Our twitter handle changed, now we are @YoQuieroSaberAR
- [x] 2) We need a new link in the menu, called "Inicio" that leads to www.yoquierosaber.org, this is to have at least a way of going back to the other site.
- [x] 3) The "attention needed" page needs to be in the header menu.

I still have doubts about the other links, as I'm not sure they make sense, but let's leave them there for the time being.

**Comment by dracos** [comment]
For 3) I need the Spanish string to use for the menu link; for 2 and 3 I need to know their positions in the menu – at the end?

**Comment by martinszy** [comment]
Ok, there's more to this, from work made last night.

This is the new menu:
Inicio
Sobre YQS -> Acerca de Yo Quiero Saber
PROVINCIA -> Candidatos por provincia
Estadísticas -> (we replace it with Attention needed page) -> Prioridades
Reutilizá YQS - > (new page) content is about using the API, split from the about page. There's also new content for the about page. If it's too complicated, we can bundle them together in the about page.

**Comment by dracos** [comment]
All should be done.

**Comment by dracos** [comment]
See e.g. http://argentina.ynr.staging.mysociety.org/help/about on our staging site.
