### ISSUE TITLE
Email is in english

### ISSUE THREAD

**Issue by martinszy** [mysociety/yournextrepresentative#459]
The sign-up verification email is sent in english

**Comment by martinszy** [comment]
Proposal for mail text in spanish:

¡Hola! ¡Gracias por ser parte de Yo Quiero Saber!

Estás recibiendo este e-mail porque te registraste en Yo Quiero Saber Investigación Colectiva. 

Para confirmar tu registración ingresa a http://argentina.ynr.staging.mysociety.org/accounts/confirm-email/xcmzw3plgdcdgvvj6gf0cutmrwvoxa8jrordyawqsl3qzx27qhvu1ezmapvjppjl/

Si no deseas esta suscripción, ignora éste mensaje.

Gracias desde el equipo de Yo Quiero Saber.

**Comment by dracos** [comment]
This is a bug in allauth which I have reported at https://github.com/pennersr/django-allauth/issues/1048
To work around it, I have used your text directly in the repo (committed in 538e059) where hopefully it will override the default.
