### ISSUE TITLE
Any errors link opens only one field

### ISSUE THREAD

**Issue by martinszy** [mysociety/yournextrepresentative#462]
In this page: http://investigacion.yoquierosaber.org/election/gobernadores-argentina-paso-2015/post/gob-15/gobernador-por-buenos-aires

The link to fix the candidate asks for the source of the information, without asking for the information.

- [ ] Remove "Not actually standing" button.

**Comment by dracos** [comment]
Could you possibly provide more information for this? If I am on that page, logged in, and I click "Edit" by a candidate, I get a form containing all the fields that you can edit. The last field asks for the source of the information, but are you saying there should be another box there? The "information" is what you have put in all the other fields in the form, if I've understood it correctly.

**Comment by martinszy** [comment]
This is the "¿Algun error?" link, not the edit link.

2015-07-23 11:40 GMT-03:00 M Somerville <notifications@github.com>:

> Could you possibly provide more information for this? If I am on that
> page, logged in, and I click "Edit" by a candidate, I get a form containing
> all the fields that you can edit. The last field asks for the source of the
> information, but are you saying there should be another box there? The
> "information" is what you have put in all the other fields in the form, if
> I've understood it correctly.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mysociety/yournextrepresentative/issues/462#issuecomment-124127808>
> .
>



-- 
*Martín Szyszlican*
Desarrollo web usable y accesible
martinszyszlican.com

**Comment by dracos** [comment]
Okay, so this appears to be a problem in translation – the English button is "Not actually standing?", ie. this button is only to say that the candidate is not standing, so all that is then needed is the source of this information. It is not a generic "report error" button.

**Comment by martinszy** [comment]
I've fixed the translation, can you update the strings?

**Comment by martinszy** [comment]
Ok, I asusme this is because you used a pre-populated list of candidates
from the past elections, right?
We don't have that, so we could de-priotitize this action?
Easy: change colour to gray, and the other action to green.
Hard: Move it to inside the editing.

2015-07-23 13:25 GMT-03:00 M Somerville <notifications@github.com>:

> Okay, so this appears to be a problem in translation – the English button
> is "Not actually standing?", ie. this button is only to say that the
> candidate is not standing, so all that is then needed is the source of this
> information. It is not a generic "report error" button.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mysociety/yournextrepresentative/issues/462#issuecomment-124158335>
> .
>



-- 
*Martín Szyszlican*
Desarrollo web usable y accesible
martinszyszlican.com

**Comment by dracos** [comment]
"Ok, I asusme this is because you used a pre-populated list of candidates from the past elections, right?" – I don't believe so, no; it was just a simple way to fix the issue of someone being listed as standing when it turned out they were not (perhaps they pulled out for some reason), independent of changing any information about them. Can ask Mark when he's back. Anyway, it is already sort of included in the editing, as you could change the "Standing" drop down to say No presumably. So we could remove it if it was not needed at all, or swap the colours as you suggest.

**Comment by martinszy** [comment]
Ok, so just remove it then.

2015-07-23 15:07 GMT-03:00 M Somerville <notifications@github.com>:

> "Ok, I asusme this is because you used a pre-populated list of candidates
> from the past elections, right?" – I don't believe so, no; it was just a
> simple way to fix the issue of someone being listed as standing when it
> turned out they were not (perhaps they pulled out for some reason),
> independent of changing any information about them. Can ask Mark when he's
> back. Anyway, it is already sort of included in the editing, as you could
> change the "Standing" drop down to say No presumably. So we could remove it
> if it was not needed at all, or swap the colours as you suggest.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mysociety/yournextrepresentative/issues/462#issuecomment-124189604>
> .
>



-- 
*Martín Szyszlican*
Desarrollo web usable y accesible
martinszyszlican.com
