### ISSUE TITLE
Missing translation in edit candidate page

### ISSUE THREAD

**Issue by martinszy** [mysociety/yournextrepresentative#463]
http://investigacion.yoquierosaber.org/person/2/update

- [x] "save changes" = Guardar cambios
- [ ] "show full version" = Mostrar versión completa
- [x] "Upload photo" = Subir foto

**Comment by dracos** [comment]
I have marked the "Save changes" for translation and it should now be okay.
The "Show full version" is in JavaScript, so I'm just setting up the appropriate code to enable JS translations.

**Comment by dracos** [comment]
Upload photo is already present in the translation, presumably it just needs the compilemessages script rerunning? It also has CSS updates, e.g. on our staging site it looks like this:

![screen shot 2015-07-23 at 20 54 45](https://cloud.githubusercontent.com/assets/154364/8860644/160a84a2-317d-11e5-8152-d8b25c5be997.png)

The live site currently looks like:
![screen shot 2015-07-23 at 20 55 03](https://cloud.githubusercontent.com/assets/154364/8860651/1e9d11a2-317d-11e5-92e1-151a14855027.png)

So needs translation and static file updating, I think.
