### ISSUE TITLE
Problem as we add more elections

### ISSUE THREAD

**Issue by martinszy** [mysociety/yournextrepresentative#464]
http://investigacion.yoquierosaber.org/person/2/update

In the edit candidate page, all elections are listed to ask weather the candidate is running for that.
This is confusing, as candidates only run for one election each.

**Comment by mhl** [comment]
This is likely to be an issue for the UK elections in 2016 as well, when we'll be supporting many elections.

**Comment by mhl** [comment]
n.b. This ticketed is about the edit form for a person, whereas the similar https://github.com/mysociety/yournextrepresentative/issues/472 is about display of the person's details on the person view page.

**Comment by mhl** [comment]
This has been dealt with by https://github.com/mysociety/yournextrepresentative/pull/968
