### ISSUE TITLE
Twitter app asks for write permissions

### ISSUE THREAD

**Issue by dracos** [mysociety/yournextrepresentative#465]
Presumably it only needs read?

**Comment by mhl** [comment]
Indeed - @martinszy created the account used for Twitter login, so he'll need to change the permissions in https://apps.twitter.com/ under the appropriate app's "Permissions" tab.

**Comment by martinszy** [comment]
This app is only for login, so it only needs read. Thanks!

2015-07-22 14:57 GMT-03:00 Mark Longair <notifications@github.com>:

> Indeed - @martinszy <https://github.com/martinszy> created the account
> used for Twitter login, so he'll need to change the permissions in
> https://apps.twitter.com/ under the appropriate app's "Permissions" tab.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mysociety/yournextrepresentative/issues/465#issuecomment-123808977>
> .
>



-- 
*Martín Szyszlican*
Desarrollo web usable y accesible
martinszyszlican.com

**Comment by martinszy** [comment]
This has been changed and should be closed.

**Comment by dracos** [comment]
Great :)
