### ISSUE TITLE
Emails are not sent

### ISSUE THREAD

**Issue by dracos** [mysociety/yournextrepresentative#466]
I do not receive any confirmation email, due to the host not having a reverse DNS entry: "450 4.7.1 Client host rejected: cannot find your hostname"

- [ ] Update the .165 address's reverse DNS to point to investigacion.yoquierosaber.org

**Comment by martinszy** [comment]
I do get emails and also people who has been testing the app, but I'll check it out

**Comment by dracos** [comment]
Yes, it's dependent on the recipient mail server being perhaps a little overzealous about spam filtering (as the one I use apparently is!), I imagine it won't apply to most people, but is quite annoying if it does :) If it's easy to add a reverse DNS entry, I would recommend it. I don't know if this is the relevant documentation for you, but in case it is: https://www.digitalocean.com/community/questions/how-do-i-set-up-reverse-dns-for-my-ip

**Comment by martinszy** [comment]
Can you try again?

2015-07-23 3:59 GMT-03:00 M Somerville <notifications@github.com>:

> Yes, it's dependent on the recipient mail server being perhaps a little
> overzealous about spam filtering (as the one I use apparently is!), I
> imagine it won't apply to most people, but is quite annoying if it does :)
> If it's easy to add a reverse DNS entry, I would recommend it. I don't know
> if this is the relevant documentation for you, but in case it is:
> https://www.digitalocean.com/community/questions/how-do-i-set-up-reverse-dns-for-my-ip
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mysociety/yournextrepresentative/issues/466#issuecomment-123999314>
> .
>



-- 
*Martín Szyszlican*
Desarrollo web usable y accesible
martinszyszlican.com

**Comment by dracos** [comment]
There's reverse DNS present now, but it is yoquierosaber.org, not investigacion.yoquierosaber.org, so it's still being rejected as not matching. I think if the .165 address could be investigacion.yoquierosaber.org then it would work.

**Comment by martinszy** [comment]
It should be fixed now

**Comment by dracos** [comment]
Great, yes, email received :)
