### ISSUE TITLE
New page: Reutilizá YQS

### ISSUE THREAD

**Issue by martinszy** [mysociety/yournextrepresentative#468]
(this is taken from the current about page to a new one, but can stay there in the meanwhile, check #443 )

Utilización de la información de Yo Quiero Saber

El código fuente de este sitio está disponible en GitHub, y podés encontrar la lista de errores conocidos ahí también. Y este es nuestrofork para Argentina, en GitHub también.

Podés usar los datos de este sitio, a través de la API o descarga CSV, bajo los términos de la licencia Creative Commons Atribución-CompartirIgual 4.0 Internacional (CC BY-SA 4.0) con la excepción de:
Los logos de los partidos.
Las fotos de los candidatos, que típicamente son enviadas por los propios candidatos, o de fuentes donde parece razonable que podamos usarlas, como la página oficial del candidato o su perfil en medios sociales.
Si la licencia CC-BY-SA le resulta problemática, por favor contáctenos para charlar sobre su situación.
La información en este sitio es producto de una investigación colectiva (crowd-source) y puede no estar completa o contener inexactitudes. Si encuentra un error, por favor actualice la página usted mismo registrándose, o envíenos un correo para reportar el problema.

- [x] Text
- [x] Links in text

**Comment by dracos** [comment]
I've added this text, but I think it still needs links :) But it's on a separate page, hope that's helpful.

**Comment by martinszy** [comment]
Links added

**Comment by dracos** [comment]
Could you submit your changes as pull requests to us so that we can hopefully keep in sync? :)
