### ISSUE TITLE
Fields cut off if they're too long

### ISSUE THREAD

**Issue by dracos** [mysociety/yournextrepresentative#474]
The field with data should read "Candidato actualmente en Diputados Nacionales PASO 2015" (there should probably only be one if we have it for this set (that is #472), but it's possible there'd be more than one and anyway it still shouldn't cut it off if there's only one).
http://investigacion.yoquierosaber.org/person/46/emilio-martinez-garbino
![screen shot 2015-07-27 at 13 44 45](https://cloud.githubusercontent.com/assets/154364/8906333/b51052da-3465-11e5-9030-605bce230f97.png)
![screen shot 2015-07-27 at 13 46 03](https://cloud.githubusercontent.com/assets/154364/8906347/d7fad3a6-3465-11e5-9bfa-3fe4dec0385a.png)

**Comment by zarino** [comment]
Pull request here: https://github.com/mysociety/yournextrepresentative/pull/518

**Comment by martinszy** [comment]
I verified this is fixed in my updated local dev environment.
