### ISSUE TITLE
Adding new candidate sometimes creates bad data, or gives error

### ISSUE THREAD

**Issue by dracos** [mysociety/yournextrepresentative#475]
Steps to reproduce:
1. http://investigacion.yoquierosaber.org/areas/PRV-15/buenos-aires, "Agregar un candidato nuevo" to e.g. "Diputado Nacional por BUENOS AIRES".
2. Set name and source to TESTING, leave party blank, click Agregar.
3. On error page (as you didn't give a party), set standing to:
    a. No and submit to get an immediate 500 on the submission
    b. Don't know and submit to get it to create an entry with bad data, such that trying to load the new person (after the "success" redirect) now gives a 500 error.

**Comment by dracos** [comment]
I'm not sure about the intricate details of this, but in summary:
* When No was selected, the lock check failed as that assumed there would be a post present in standing_in when there wouldn't be - solution, make sure standing_in has something;
* When Don't know was selected, standing_in locally appears to be the empty dictionary `{}` - yet the entry created on popit has no entry at all, which causes the issue on view. View solution is to make sure the standing_in property is always used no matter what data it may have got or not got, but I haven't worked out why the empty dictionary isn't being stored at all, perhaps empty dictionaries are skipped somewhere?

**Comment by mhl** [comment]
For the record, the latter part is explained by this PopIt bug:

* https://github.com/mysociety/popit/issues/710
