### ISSUE TITLE
processing of images in the moderation queue breaks transparency

### ISSUE THREAD

**Issue by mhl** [mysociety/yournextrepresentative#478]
For example, we've uploaded the following image of Manuela Castañeira from:

* http://elecciones2015.yoquierosaber.org/static/img/candidatos/manuela-castaneira.png

![Original image of Manuela Castañeira](http://elecciones2015.yoquierosaber.org/static/img/candidatos/manuela-castaneira.png)

... but once approved, this image is broken on the site:

![broken-image-transparency](https://cloud.githubusercontent.com/assets/7907/8956198/3764feee-35eb-11e5-8222-9c6ccf4e37cb.png)

Some quick testing suggests that this is due to the processing with Pillow here:

* https://github.com/mysociety/yournextrepresentative/blob/509e570acf73e1c38d48e43a2000c3ab57c5aed1/moderation_queue/views.py#L210-L216

... rather than the PopIt image proxy, since the original image is can be proxy without those artefacts:

* https://ynr-argentina.popit.mysociety.org/image-proxy/http%3A%2F%2Felecciones2015.yoquierosaber.org%2Fstatic%2Fimg%2Fcandidatos%2Fmanuela-castaneira.png/100/100

![fine through proxy](https://ynr-argentina.popit.mysociety.org/image-proxy/http%3A%2F%2Felecciones2015.yoquierosaber.org%2Fstatic%2Fimg%2Fcandidatos%2Fmanuela-castaneira.png/100/100)

**Comment by mhl** [comment]
Actually, the image-proxy is removing the transparency too, it's just that it's replacing it's blending it with white instead of showing the underlying data in the non-alpha channels.

**Comment by lizconlan** [comment]
not ideal in either case but we can probably live with either stripping the alpha channel or blending with white

**Comment by lizconlan** [comment]
deceptively simple :+1:
