### ISSUE TITLE
Candidates not showing on correct pages

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/yournextrepresentative#486]
From @martinszy 

This page shows we have 40 candidates for diputado nacional por buenos aires:
http://investigacion.yoquierosaber.org/numbers/attention-needed

And this page shows none:
http://investigacion.yoquierosaber.org/election/diputados-argentina-paso-2015/post/dip-15/diputado-nacional-por-buenos-aires

And later:

This problem keeps getting worst.
We have hundreds of entries now for buenos aires and ciudad de buenos aires that are not showing on the appropiate pages.
http://investigacion.yoquierosaber.org/election/diputados-argentina-paso-2015/post/dip-8/diputado-nacional-por-ciudad-autonoma-de-buenos-aires

I invalidated the cache. 
The nginx cache is disabled.
The cloudflare cache is not caching html.
Other pages are getting updated instantly.

**Comment by dracos** [comment]
This is oaky now, I flushed memcache. memcache should be being invalidated when data is updated, and is for us, so there is some sort of issue around this, but it can be worked around by flushing.

**Comment by mhl** [comment]
We hope that b61eab499 will address the underlying cache invalidation issue, so I'm going to close this now.
