### ISSUE TITLE
Place major parties to top of party list in admin interface

### ISSUE THREAD

**Issue by paullenz** [mysociety/yournextrepresentative#49]
Currently the admin interface drop down selection lists all parties alphabetically. There are hundreds.

Instead it is proposed that the top five parties are listed at the top alphabetically, with the remainder beneath a dotted line:

Conservatives
Green
Labour
Lib Dem
UKIP

**Comment by mhl** [comment]
This was done in: https://github.com/mysociety/yournextrepresentative/pull/822
