### ISSUE TITLE
AR: National Posts for MercoSur parliamentarians

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/yournextrepresentative#491]
From @martinszy : I'm adding a second national post for the mercosur (Note from Jen; Similar to MEPs) parliamentarians representing the whole country.

I think I should be able to see them somewhere, for example here:
http://investigacion.yoquierosaber.org/areas/NAT-0

But it says it's malformed.

I got there from here:
http://investigacion.yoquierosaber.org/areas-of-type/NAT

So I think this is at least a bug.

I created this link:
http://investigacion.yoquierosaber.org/election/parlamentarios-mercosur-unico-paso-2015/post/pmeu/

That works, but it's still empty

**Comment by JenMysoc** [comment]
Matthew commented: That error is shown when an UnknownPostException is raised, so you
could add some debugging print statements or logging around the call
to get_post_cached in candidates/views/areas.py to see what data is
trying to be looked up at that point.

My guess is it looks like it's trying to look up the post ID "pres"
whereas the ID in your popit instance is "presidente", so this error
actually existed before this second national post if that is the case.

**Comment by martinszy** [comment]
I'm sorry this got delayed, we should take a look soon.

**Comment by mhl** [comment]
I think this error was fixed with b847647f43caec6a71a49bceac6d1, so I'm closing it - we should be updating YQS to latest master today, so if this is still an issue after that we can reopen it.
