### ISSUE TITLE
[AR] Add the ability to fix an order in the data when it goes into the database

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/yournextrepresentative#496]
When speaking to @martinszy today he mentioned that changing the way data is modelled would help them immensely. 

There's an order to the way they scrape data about candidates for the elections which is related to the fact that there are usually a far larger number of candidates than posts and it quickly becomes clear which candidates have a chance and which don't. The ability to impose an order of importance on the data that goes into the database which stays when the data is in the database would help people prioritise which candidates need data collecting and which are less important and could be left without data.

**Comment by martinszy** [comment]
As an example, you can look at the column "posición" in this table:
https://github.com/YoQuieroSaber/dinescrap/blob/master/salida/BUENOS%20AIRES.csv

**Comment by martinszy** [comment]
Is this dependent on #500 ?

**Comment by martinszy** [comment]
I think this may be solved by https://github.com/mysociety/yournextrepresentative/commit/46b7c4e79f7fecd9 and #524

**Comment by martinszy** [comment]
This is working in local dev environment, needs more testing.

**Comment by martinszy** [comment]
I think it doesn't add the party_position property to memberships that were created by the users.
This is the import script:
https://github.com/mysociety/yournextrepresentative/blob/65554ef7b63705b78b09b499ede5905dc9f44113/elections/ar_elections_2015/management/commands/ar_elections_2015_import_candidates_csv.py

And I will not be certain about this until we don't have all the alliances in the db
https://github.com/mysociety/yournextrepresentative/issues/487

**Comment by martinszy** [comment]
The case in which I wasn't seeing the property being added is person 49, gabriel solano. But I realized the name in the import file didn't match the candidate name added by the user, so it's duplicated, which is a different issue.
I'll continue testing.

**Comment by mhl** [comment]
The party list support now fixes this issue, and @martinszy said when we were talking that he's fine with this being closed now.
