### ISSUE TITLE
Create simple YNR for Burkina Faso

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/yournextrepresentative#501]
We need to know:

- What the elections process is?
- How the seats in the National Assembly are associated geographically?
- Would we have to support party lists?
- How do you indicate a preference for candidates on the ballot paper?
- Data about the politicians that needs to be loaded in
- Translation for the site
- Where to find an authoritative list of the political parties that people might be standing for (Ideally from a source that has a unique ID for each party.)
- The election date for each type of election (and if all the elections aren't happening on the same day, that would be good to know!)
- What's the name of the posts people are being elected to?  (eg: Député ou similaire)
- What are the official names of the elections (e.g. "2010 General Election", "Presidential Election")
- What was the date of the previous general and presidential elections?

before we can set this up.

**Comment by Gemmamysoc** [comment]
Responses:

- A good understanding of the electoral system.
   + Pridential
The presidential elections are held by the majority system in two rounds. The candidate who obtains an absolute majority of votes cast in the first round is declared elected. When the absolute majority of votes cast is not obtained on the first round by a candidate, the Constitutional Council shall adopt and publish the list of two candidats eligible to sit for the second round. The candidate who obtains a simple majority in the second round is declared elected
   + Legislative
We have only one chamber for that elections. There are 127 seats at the national assemblee elected by proportional representation. 16 MP are elected at national level (the associated geographical constituency is national territory) and for the 111 others, the constituency is the province.
I have attached the data we used in 2013 for the nosdeputes.bf project. We got it with the national geographical institute.
 - Where to find an authoritative list of the political parties that people might be standing for (Ideally from a source that has a unique ID for each party.)
The liste that is online is in PDF, we must take at a reusable format with the commission today.
- The election date for each type of election (and if all the elections aren't happening on the same day, that would be good to know!)
    + Presidential : 11 October 2015
    + Legislative : 11 October 2015
- What's the name of the posts people are being elected to? (In French and other languages you want to support) (eg: Député ou similaire)
    + Presidential : Président du Faso
    + Legislative : Député
- What are the official names of the elections (e.g. "2010 General Election", "Presidential Election"), again in French and other languages that you want to support.
    + Prisidential : Elections Présidentielles de 2015
    + Legislative : Elections Législative de 2015
- What was the date of the previous general and presidential elections?
    + Presidential : 21 November 2010
    + Legislative : 02 December 2012

I have not yet the liste of candidates will send later.

**Comment by Gemmamysoc** [comment]
List of political parties: http://opendata.gov.bf/dataset/commission-electorale-nationale-independate/resource/ed8af32a-9683-44c1-b8d7-a81d1fb1b1af

**Comment by Gemmamysoc** [comment]
Another response form Tinto:

- How do you indicate a preference for candidates on the ballot paper?

The way you indicate your preference is not yet establisshed by the electoral commission, but during the last election[1], you put your finger on a rag soaked in ink, and you leave the imprint of your finger next to the logo of your candidate. I will confirm it soon.

[1] http://sahelresearch.africa.ufl.edu/files/2012-municipal-elections-in-Burkina-Faso.jpg

**Comment by Gemmamysoc** [comment]
Another response from Tinto:

Would we have to support party lists?

It is a party list proportional representation. Each party submit a list of their candidates, and each candidates have a substitute. after the election, il a candidates have been elected, he can choose to let the seat for his substitute.

PS: Because of the new electoral code, many candidates that supported the modification of the constitution that lead to the revolution are declared  ineligible. So the list is updated regularly, that is why we are still waiting for the final one
