### ISSUE TITLE
switch to using onBehalfOf on Candidate Memberships instead of separate party memberships

### ISSUE THREAD

**Issue by mhl** [mysociety/yournextrepresentative#502]
As @tmtmtmtm has pointed out, the recommended way now of representing that someone's standing as a candidate for a paritcular party is to use the [onBehalfOf property of a Membership](http://www.popoloproject.com/specs/membership.html) of role "Candidate" to refer to the party's Organization. This deals with the conceivable case of someone standing for one party while they're primarily a member of another, and has the practical benefit of meaning that each candidacy can be represented by only one membership rather than two, which is more elegant and will be less confusing to data reusers.

**Comment by akuckartz** [comment]
Can this represent the case that someone is standing for several parties?

**Comment by tmtmtmtm** [comment]
@akuckartz — do you have an example of this? I suspect the approach would differ slightly depending on whether it's a single candidacy, along the lines of people in the UK standing jointly as "Labour and Co-operative", or whether it's effectively two different simultaneous candidacies, each for a separate party.

**Comment by mhl** [comment]
We've migrated to using `on_behalf_of` and using a single membership to represent a candidacy in 9e632089cc38cff5
