### ISSUE TITLE
Sass bug

### ISSUE THREAD

**Issue by evz** [mysociety/yournextrepresentative#511]
It looks like this declaration: https://github.com/mysociety/yournextrepresentative/blob/master/candidates/static/candidates/_content.scss#L14-L16 is throwing a compile error:

```
".button" failed to @extend ".radius". (Sass::SyntaxError) The selector ".radius" was not found.
```

**Comment by dracos** [comment]
I think that's an issue with a too-recent version of sass. If you use 3.2.19 (which is the version the deployment script installs, looks like), it seems to be okay. Not sure what changed in sass that means it now isn't.

**Comment by mhl** [comment]
What version of sass are you using? If I remember right, this is the error you get when using a more recent version of sass than 3.2.9

**Comment by evz** [comment]
Looks like I have 3.4.18. I'll go ahead and downgrade.

**Comment by mhl** [comment]
(Snap!) I made a typo, though - I meant 3.2.19 as well. @zarino - could you possibly look at changing this Sass so it works with more recent versions too if you have a moment to look at that?

**Comment by evz** [comment]
FWIW, downgrading to 3.2.19 seems to have worked.
