### ISSUE TITLE
support for party lists in PR systems

### ISSUE THREAD

**Issue by mhl** [mysociety/yournextrepresentative#514]
An important way in which YNR is lacking at the moment is that it doesn't offer any support for elections where there is a party list system. Typically this will be for an election that uses some form of proportional representation - each party will have an ordered list of candidates for a particular post; if they gets lots of votes, then the first few candidates on the list will be election, or if they do less well, perhaps just the first person on the list would be elected.

At the moment, you can add multiple candidates of the same party for a post, but they're all shown, which isn't ideal - those lower down the list have very little chance of getting in.

I think the work for this will probably involve:

* Adding a optional fields to the `ELECTIONS` values called something `party_lists` (a boolean) and `party_list_members_to_show` (integer)
* For elections where `party_lists` is `True`, when you're editing the candidacy allow the user to enter their position on the party list (1, 2, 3, etc.)
* When listing candidates in an election where `party_lists` is `True`, group the candidates by party and order by their position on the party list.
* Using Javascript, hide all but the first `party_list_members_to_show` by default, with a link to click to show the rest of them, or (non-Javascript) have link you can click through to get page with the whole list.

**Comment by zarino** [comment]
Styling for this should be simple. The hard bit will be making it work with and without javascript.

**Comment by mhl** [comment]
Almost all done in: https://github.com/mysociety/yournextrepresentative/commit/46b7c4e79f7fecd90c98a40871eaba1320b6053c

... although in the end we decided to make it all not dependent on javascript - you just click through to see the full party list.
