### ISSUE TITLE
Move Election settings into a model

### ISSUE THREAD

**Issue by struan** [mysociety/yournextrepresentative#526]
Create an Election model (and register it with the Django admin) to replace the definition of elections in the ELECTIONS data structure in elections/*/settings.py. This should hopefully make the setup of election in a new site somewhat easier. Replace existing references to ELECTIONS and the settings derived from it with references to the Election class. (e.g. ELECTIONS_CURRENT should instead be a method on a custom manager for the Election model.)

Part of #500

**Comment by mhl** [comment]
Fixed in:
* f04f488b1b64
* 9a3336f3580a79e00
* d438d4fef6e7f8e
* e41d46fe0539
* 82435eaaabec7a
* 8ea4af41b44d68
* f99179ef55f05792e
* 01bf5750f036faa2
