### ISSUE TITLE
Allow to configure a set of extra fields for a candidate

### ISSUE THREAD

**Issue by martinszy** [mysociety/yournextrepresentative#529]
Add more information about candidates, for example:

- [ ] Ballot (actually related to many candidates)
- [ ]  Link of TV or radio advertisements. Broadcasters are required by law to emit these.
- [ ]  News mentions
- [ ]  Stances, with source link
- [ ]  Asset declaration
- [ ]  Full biography
- [ ]  Political career (link to cargografías

**Comment by mhl** [comment]
There is now generic support for adding additional non-Popolo fields in the admin interface via the `ExtraField` model. I guess this is no longer relevant for YQS, however, @martinszy, so can we close this issue?
