### ISSUE TITLE
pick a Django row versioning package

### ISSUE THREAD

**Issue by mhl** [mysociety/yournextrepresentative#556]
There are various options for versioning Django models: https://www.djangopackages.com/grids/g/versioning/

For YNR, we'll need to version relationships to rows in other tables, which makes it look like the two best options are:

* http://django-reversion.readthedocs.org/en/latest/
* https://github.com/swisscom/cleanerversion

We should evaluate at least these two, and update the importer to reconstruct the past version history.

This depends on #553

**Comment by stevenday** [comment]
If it helps, we've used django-reversion before in a commercial project (for the NHS) and found it quite nice.  We [wrote a few helpers for displaying version history](https://github.com/mysociety/citizenconnect/blob/28ae4fc46bd1fdfd37a9ecad71402bc558c7b15c/issues/lib.py#L12-L88) that might be useful.

**Comment by mhl** [comment]
Thanks, @stevenday

**Comment by struan** [comment]
See https://docs.google.com/document/d/1vkDpFLlhl2NsGB3uCreor7pYperPrg3d2LKpVqbIObQ/edit# for notes.

Probably django-reversion is the best suited but it's still not ideal because the support for relationships isn't great.

**Comment by struan** [comment]
For the moment the plan is to just port the existing versioning mechanism and not use a third party versioning model.
