### ISSUE TITLE
Make photo moderation queue work for any election

### ISSUE THREAD

**Issue by struan** [mysociety/yournextrepresentative#568]
Currently there's some hard coding in the photo moderation queue which means it will only work for candidates in the 2015 uk general election.

**Comment by mhl** [comment]
Is this the bit you're thinking of https://github.com/mysociety/yournextrepresentative/blob/master/moderation_queue/views.py#L129-L134 or is there something else?

**Comment by struan** [comment]
That's the bit. And looking at that again it will still work for other elections. Just not do the constituency so my description is clearly a bit overblown.

**Comment by mhl** [comment]
Fixed in 70e84cc6cf4df088e109
