### ISSUE TITLE
Group together similar elections

### ISSUE THREAD

**Issue by tfgg** [mysociety/yournextrepresentative#598]
E.g. on https://edit.yournextmp.com/posts although "2016 London Assembly Election (Constituencies)" and "2016 London Assembly Election (Additional)" are separate elections for YNR's purposes as they have different election methods, it'd be helpful to group them together as "2016 London Assembly Election".

The group names could be higher-level election identifiers (#597), e.g. "gb-gla-2016-05-05" groups together "gb-gla-2016-05-05-a" and "gb-gla-2016-05-05-c".

**Comment by mhl** [comment]
Let's just do a UK specific view and template override of this page; if it comes up in another country we can think about a more generic solution.

**Comment by mhl** [comment]
We've come across another case where it would be nice if the data model supported grouping elections. @tfgg tells us that while the EC in the UK regulates the PCC election as a single election, but mayoral elections are regulated as separate elections. If we want the data model to follow how the state models elections (which @symroe has said is desirable) it would be helpful to be able to model that the mayoral elections are all the same kind of election, in some sense.

We could already do this by grouping the posts on that page by the post's `role` attribute and then the elections as a group underneath that. That might work rather well, actually.

**Comment by jf1** [comment]
+1 from me on this, especially to improve pages that list all elections (currently rather chaotically) such as https://candidates.democracyclub.org.uk/posts

Can I add a +10 for sorting all these lists alphabetically too?

The current /posts page only seems useful for SEO - it's impractical for a human to use apart from searching within the page (for which a search facility may be a better option). If the various elections/posts were presented as an (initially collapsed) tree view then people would be able to navigate to their area of interest fairly quickly.

My grouping suggestion would be:
```
Devolved Assemblies and Parliaments
 - 2016 London Assembly Election
 - - Assembly Member for Barnet and Camden
 - - etc
 - 2016 Northern Ireland Assembly Election
 - 2016 Scottish Parliament Election (Constituencies)
 - 2016 Scottish Parliament Election (Regions)
 - 2016 Welsh Assembly Election (Constituencies)
 - 2016 Welsh Assembly Election (Regions)
Mayoral Elections
 - Bristol
 - etc
PCC Elections
 - all 
Metropolitan LAs
 - all metropolitan areas (definitely sorted alphabetically, possibly grouped by county)
Unitary LAs
 - all unitary areas (definitely sorted alphabetically, possibly grouped by county)
District LAs
 - all district areas (definitely sorted alphabetically, possibly grouped by county)
```

Here I'm using 'election' as the general public would, ignoring any EC regulators/regulations...
Ultimately I'd prefer the London/Scottish/Welsh elections to have their local and regional/additional posts combined into one list containing all posts within that election, whether or not people get one vote or two, but that's probably a separate debate that I'm just flagging up so any future code can consider this scenario.

nb. The suggestion to group local authorities by Metropolitan/Unitary/District status is purely to make the (sub-)list(s) a more practical size - there's no implication that M/U/D areas differ from each other, or that all eg M areas are the same.
