### ISSUE TITLE
Multiple organization election

### ISSUE THREAD

**Issue by evz** [mysociety/yournextrepresentative#602]
Just checking out the new Popolo changes and I'm curious as to why there is a one-to-many relationship between the Election model and the Organization model. I'm not sure how common this is in various parts of the world but it would seem that for any given election, you're probably going to be electing people to more than one organization. So, for instance, here in the US, states will have an upper and lower chamber which I'd describe as separate organizations but, more often than not, we vote for Posts in both of those organizations on the same day (as well as potentially local or county level organizations in some jurisdictions). In the former PopIt backed version I was able to describe an Election which had several Organizations like so: https://github.com/mysociety/yournextrepresentative/blob/93ff507d96d8b24690b734a9784870decf9a6747/elections/st_paul_municipal_2015/settings.py#L7-L44 (in that example there are Posts being voted on for both the City Council and the School Board). 

Perhaps I'll take a crack at submitting a pull request that addresses this (unless there is some major reason you've made that relationship work that way).

**Comment by dracos** [comment]
Hi, I'm not involved that much in this repo, but I'm not already away on Christmas ;-) So I'll say I *think* that your quoted code is for two 'elections' (there are two keys in your `ELECTIONS` dict), so I don't think anything has changed model-wise, it would transfer across as two Elections. I believe the idea is an Election is for one organisation, yes, and note many such elections may occur on the same day. For example, in May this year, the UK had a UK Parliament election, plus many council elections to lots of different councils across the country. This was many different elections, each to one organisation, not one election covering many organisations. Grouping multiple elections appears to be e.g. #598. Sorry if that doesn't make sense, or worse, is wrong, but I think that's what I've understood.

**Comment by tfgg** [comment]
For YNR I'd distinguish between an Event (going to the polls on a certain
day) and an election (voting for posts in the same organisation).

**Comment by evz** [comment]
Oh, so one should just create several Elections within one's election app? One for each Organization with Posts being elected?

**Comment by dracos** [comment]
Yes, I believe that is the equivalent of each key in the old `ELECTIONS` dictionary.

**Comment by evz** [comment]
Thanks, that helps. Sorry for the confusion! Have a good break.
