### ISSUE TITLE
new site design for Costa Rica

### ISSUE THREAD

**Issue by mhl** [mysociety/yournextrepresentative#609]
From @JenMysoc's notes:

* Elections date is Sunday 7th February 2016
* We need to start quickly in January with a staging site up by January 8th and the real site available for January 11th

It's not clear if we'll have time to do any significant customization of the site in this time, but this ticket is a placeholder for any such design work.

**Comment by zarino** [comment]
I've started in branch https://github.com/mysociety/yournextrepresentative/tree/609-costa-rica-theme

![screen shot 2016-01-07 at 13 44 32](https://cloud.githubusercontent.com/assets/739624/12171844/f3da5bd6-b544-11e5-9228-5eb0c158e50c.png)

Haven't been able to test the inner pages yet – the candidate listing page and the individual candidate page will need a check over before this is good to merge.

**Comment by tmtmtmtm** [comment]
Can this ticket be closed, or is it being left open as a placeholder for other design things?

**Comment by zarino** [comment]
I think they are happy with the new theme, so we can close this.
