### ISSUE TITLE
Error when adding a new post in admin

### ISSUE THREAD

**Issue by lfalvarez** [mysociety/yournextrepresentative#610]
Hey there:
I get this message when trying to add a new post in the admin section

```
FieldError at /admin/popolo/post/add/

Unknown field(s) (membership) specified for Post. Check fields/fieldsets/exclude attributes of class PostAdmin.
``` 

I believe it is due to [this lines](https://github.com/mysociety/django-popolo/blob/update-with-better-migrations-redux/popolo/admin.py#L49-L62) and I'm wondering if there was ever a membership among the attributes for the [Post class](https://github.com/mysociety/django-popolo/blob/update-with-better-migrations-redux/popolo/models.py#L163).

**Comment by mhl** [comment]
Hi @lfalvarez - sorry about that, and thanks for pointing out the error. I've pushed a fix to the `update-with-better-migrations-redux` branch of our fork of `django-popolo`, so a `pip install -r requirements.txt` should fix that for you. I also put the same fix in a pull request for the upstream django-popolo here: https://github.com/openpolis/django-popolo/pull/25

I hope that's all OK.

**Comment by lfalvarez** [comment]
Hey @mhl ! Thanks a lot for your incredibly quick answer =).
Everything is fantastic :sparkles:
