### ISSUE TITLE
[CR] Removing candidate number from recent changes and replacing with candidate's name

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/yournextrepresentative#621]
Where the main page lists the Recent Changes, it says, for example: "El usuario xxxxxxx actualizó al candidato #5, hace 1 minuto"

Can this be changed so that the name of the candidate appears, not just his or her number?

**Comment by mhl** [comment]
I think this will mean we could probably close: https://github.com/mysociety/yournextrepresentative/issues/155 too (there might be another ticket for this but I couldn't find it on a quick search)
