### ISSUE TITLE
[CR] Name of page is cutting off on CR YNR

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/yournextrepresentative#625]
From them: "The whole title should appear: "Página del candidato en el sitio del partido" but currently in the candidate's profile it says "Página del candi...""

![screen shot 2016-01-11 at 10 22 58](https://cloud.githubusercontent.com/assets/4170351/12231224/ccda1c18-b84d-11e5-9a2f-8fd5799ef5ef.png)

**Comment by struan** [comment]
@zarino Can you suggest a solution for this?

**Comment by zarino** [comment]
@struan: You should just be able to remove the `key-value-list` class from the `<dl>` element in question, and it'll stop the two-column layout on wide screens, meaning none of the text will be truncated.

**Comment by struan** [comment]
Fixed in 7e73003abdfefc11cfb0f424c58fcf8f3c586d9d
