### ISSUE TITLE
[CR] Change the subtitles on the homepage

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/yournextrepresentative#627]
From the team:

"In the upper part of the main page there's a subtitle that says  "No le pagues a un proveedor de bases de datos -- es un desperdicio de dinero.""

"This text must be changed to "Buscá o agregá información sobre los candidatos para las próximas Elecciones Municipales del 7 de febrero""
![screen shot 2016-01-11 at 11 32 20](https://cloud.githubusercontent.com/assets/4170351/12232505/02acdcfa-b857-11e5-84f4-eee71f185bba.png)

**Comment by struan** [comment]
Fixed in 52803120df870e8f680a732bccb5adc557a740a8
