### ISSUE TITLE
[CR] merge the two columns into one on the homepage

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/yournextrepresentative#628]
![screen shot 2016-01-11 at 11 32 20](https://cloud.githubusercontent.com/assets/4170351/12232520/38cf1136-b857-11e5-80c6-ceada4d8234c.png)

The Part which in english reads: "This is a crowdsourced database...."

"These two columns of text must be joined into a single one that says: ""Esta base de datos de candidatos es producto de una investigación colectiva y está disponible como datos estructurados, lo que permite hacer otras aplicaciones con esta información. Obtené los datos ahora, o colaborá con más detalles de los candidatos.""

**Comment by struan** [comment]
Fixed in 091e139a207f7f5d48a2dbf1bfcb4951c2b8bb18
