### ISSUE TITLE
[CR] Add Accesa's user accounts to the "Photo Reviewers" group

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/yournextrepresentative#630]
Accesa would like to be able to moderate the pictures added to the site so they will need to be added to the service that allows this.

**Comment by mhl** [comment]
I've explained this by email - the only things left to do is:

- [ ] Give Accesa users permission to change group memberships of users once the live site is up
- [ ] Explain how to add people to the "Photo Reviewers" group in the admin interface

**Comment by mhl** [comment]
Done now
