### ISSUE TITLE
[CR] Add new fields to profile page

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/yournextrepresentative#633]
Add categories "Profesión", "Cargos importantes" and "Re-elección (si o no)"

**Comment by mhl** [comment]
I've added "Profession" in dc211460b1278. Is "Cargos importantes" just meant to be free text (potentially multi-line)?  I guess "Re-elección" really has to be "yes", "no" or "don't know" as options?

**Comment by JenMysoc** [comment]
Cargos importantes is like important roles or responsibilities so yes I
think a small free text box would be good. Agree on the reelection response
options :)

**Comment by mhl** [comment]
I've added "Important Roles" too now (although we need to add that string to a new file like `candidates/for_translation.py` so they'll appear in Transifex for translation, or something similar...)
