### ISSUE TITLE
Get Wikipedia pages for all incumbent MPs

### ISSUE THREAD

**Issue by tfgg** [mysociety/yournextrepresentative#65]
Pretty much all incumbent MPs will have Wikipedia pages. This could even be automated to an extent, perhaps even over all people in the DB with a simple (command line?) interface to sanity check the name to article match.

Getting wikipedia pages allows pulling in of good photos and biogs.

**Comment by sjorford** [comment]
Two of those 21 by-elections returned the previous incumbent (Carswell and Reckless), so there have been 669 MPs total in this parliament. I have added the missing three to the Wikipedia category (Robert Jenrick, Francie Molloy and Steve Reed), so it is now complete.

**Comment by mhl** [comment]
I believe, thanks to everyone's hard work, we have a complete set of Wikipedia pages both for MPs since the 2010 election, so I'm going to close this now.
