### ISSUE TITLE
[CR] The Mayoral elections have disappeared from Tus Representantes Locales

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/yournextrepresentative#650]
From Manfred:
"we were in the process of adding candidates when suddenly all the Mayors dissapeared from the site. In fact, we can't access anything from the Elección de Alcaldes. "

http://tusrepresentanteslocales.co.cr/posts

Do we need any further information?

**Comment by mhl** [comment]
Fixed in dfba9076a12b659fb and we restored the data.
