### ISSUE TITLE
[CR] 'Foo' appears at the top of the form when you press the "Add a new candidate" button

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/yournextrepresentative#667]
When you select "Add a New Candidate" at the bottom of a Party List the form displays but the word "foo" appears at the top of it. Please could we remove this? 
![screen shot 2016-01-20 at 10 02 59](https://cloud.githubusercontent.com/assets/4170351/12445715/e1d3e006-bf5d-11e5-911b-c1bba566dd73.png)

**Comment by struan** [comment]
Fixed in f63d6889f21175d1e4223b286bb6ba15868ac5e9
