### ISSUE TITLE
Context in translation strings

### ISSUE THREAD

**Issue by wfdd** [mysociety/yournextrepresentative#673]
When generating the PO files, would it be possible to include a snippet of the surrounding text in the template or the HTML tag the translation string's contained inside to provide some context?  If all I've got to go by is

```po
#: elections/uk_general_election_2015/templates/base.html:27
#: mysite/templates/generic_base.html:75
msgid "Numbers"
msgstr ""
```

I'd probably think to use a literal translation; but that's actually the text of the link to the statistics page, and a literal translation would be less-than-ideal.

If this functionality doesn't exist, I suppose we'd have to take it upstream.  (Is it Babel that generates these files?)  Perhaps a more pragmatic option would be to (additionally) identify translation strings by their function and a short description (e.g. `link in main menu:Numbers`).  Obviously, that's not gonna obviate the need to double-check our translation in the UI, but I imagine it'd reduce the error rate.

Does anybody have prior experience with gettext?  How do other large projects deal with this issue?

**Comment by wfdd** [comment]
Related: #353.

**Comment by wfdd** [comment]
On further thought, this is probably best solved by using an application that'll automatically skip to the lines in the source(s) provided - if any such application exists.  I suppose I'll leave the issue open should anybody have any input.  (Or the project's maintainers can close it if they wish.)

**Comment by dracos** [comment]
Contextual markers can be supplied in the source code that feed through to the .po file as described at https://docs.djangoproject.com/en/1.9/topics/i18n/translation/#contextual-markers

I know emacs has e.g. po-cycle-source-reference which will open up the source file from the translation you are on in PO mode.

**Comment by wfdd** [comment]
Oh very good, thank you.  Would modifying some of these translation strings to use contextual markers be welcome?

**Comment by mhl** [comment]
@wfdd - Yes, certainly adding contextual markers for any translation string that would be otherwise be ambiguous to you would be very welcome.
