### ISSUE TITLE
Remove mention of PopIt from the standard /help/api page for YNR

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/yournextrepresentative#685]
http://tusrepresentanteslocales.co.cr/help/api for example still mentions PopIt and links to it on the Poplus site, as does http://investigacion.yoquierosaber.org/help/api

We probably just need to re-write the standard text at the top of this page to let people know what we are using now.

![screen shot 2016-02-04 at 09 43 33](https://cloud.githubusercontent.com/assets/4170351/12811358/d70f16e6-cb23-11e5-933b-a6bcd9b9dede.png)

&

![screen shot 2016-02-04 at 09 44 29](https://cloud.githubusercontent.com/assets/4170351/12811374/f1bff0d2-cb23-11e5-947c-91fb60197a54.png)

**Comment by mhl** [comment]
Fixed in f0fffc2748ea86c8aa and deployed for edit.yournextmp.com - I've pushed the string to Transifex so we should wait for a translation before deploying that for Costa Rica.
