### ISSUE TITLE
transfer twitter apps for social logins from personal accounts to the @mysociety account

### ISSUE THREAD

**Issue by mhl** [mysociety/yournextrepresentative#686]
Previously this wasn't possible because the mysociety Twitter account didn't have an associated phone number - now it does, we can transfer the Twitter apps. @mhl has a couple, and @struan has one.

It looks like you can do this here:

https://support.twitter.com/forms/platform

**Comment by mhl** [comment]
On that page, select the "I need to transfer an API key to another account" option. Find the details of the app from https://dev.twitter.com/apps/ - some hints:

* **Application Name** (I think) this is the name in the `<h1>` on the page for your app (and the name listed on the front page of: https://dev.twitter.com/apps/ )
* **Application ID** This is the number in the URL once you click on the app in https://dev.twitter.com/apps/
* **Consumer Key** This is on the details tab once you select the app from https://dev.twitter.com/apps/
* **Application URL** I think this is the URL right under the description of the app on the details tab of 
* **Transfer To**: `@mysociety`
* **Details**: "This is used for social login for one of `@mysociety`'s sites - I had to create this with my personal account because at that point there was now verified phone number for the `@mysociety` account. There is now, so we're moving such applications from personal accounts to the charity's account."

I've done this for all of mine now, which are:

* YNR Argentina (staging)
* YNR Burkina Faso (staging)
* YNR Burkina Faso (staging) 2
* YNR Burkina Faso (production)
* YNR Costa Rica staging
* Tus Representantes Locales

It would be great if you could do the same for your one, @struan.

**Comment by struan** [comment]
Done
