### ISSUE TITLE
allow you to customize the number winners on a per-post basis

### ISSUE THREAD

**Issue by mhl** [mysociety/yournextrepresentative#691]
At the moment you can say that every post in a particular election may have N people elected to it (or for the number of winners to be unrestricted). However for the Costa Rican Regidor elections there may be a variable number of people elected depending on the post.

It would be nice (as @tmtmtmtm suggested in #582) if the data model supported overriding the election-wide number of winners per post. Note that this shouldn't just be a property of the post, though, since it's quite conceivable that the number of people elected per post is different between for that post in different elections. So probably this needs to be [an attribute on the ManyToManyField relationship](https://docs.djangoproject.com/en/1.8/topics/db/models/#extra-fields-on-many-to-many-relationships) between PostExtra and Election.

**Comment by wfdd** [comment]
Intuitively, this would be a property of the constituency (area).

- Election has Area.
- Area has _x_ of Post in Election.

**Comment by mhl** [comment]
Fixed in the linked pull request
