### ISSUE TITLE
Create "nomination" model

### ISSUE THREAD

**Issue by martinszy** [mysociety/yournextrepresentative#698]
Nominations are ways candidates can become elected without an election.

A nomination is a type of Popolo Membership as described here:
http://www.popoloproject.com/specs/membership.html

Part of #697

**Comment by tmtmtmtm** [comment]
There are also many other ways that people can hold office without an election. Would we need a new model for each of them?

**Comment by martinszy** [comment]
In my country you either have all nominations are published in the National Bulletin.
It's true that you can be contracted or sub-contracted, but I'm not sure that would be in scope for the site.
Do you think we can make a moel to accomodate all different ways of holding office and having the model have a field for name for that type?

**Comment by martinszy** [comment]
Moving this issue to the Conocimiento Abierto fork.
