### ISSUE TITLE
Remove candidate's dependency on party

### ISSUE THREAD

**Issue by martinszy** [mysociety/yournextrepresentative#700]
Party is no longer a mandatory field. Not all public servants belong to a party, only those who have gone trough an election or have a strong affiliation with a party.

Part of #697

**Comment by tmtmtmtm** [comment]
1. People can also stand for election without a Party. However it's generally useful to be able to distinguish between someone being _known_ to have no Party affiliation, and it not (yet) being known whether someone has such an affiliation or not. 

2. If the goal is to be able to handle more information about politicians post-election, then, if anything, the approach needs to be extended to cope with the fact that in much of the world the political affiliation within a legislature is to a faction or grouping, which can be (and often is) distinct from their party (either or both of which can be 'None')

**Comment by martinszy** [comment]
Moving this issue to the Conocimiento Abierto fork.
