### ISSUE TITLE
Rename "candidate" model to "politician"

### ISSUE THREAD

**Issue by martinszy** [mysociety/yournextrepresentative#701]
Once all changes in #697 are done, a candidate will no longer be just a candidate, but also any politician in office. I suggest renaming the model.

**Comment by tmtmtmtm** [comment]
Is a person who stands in election and loses still a politician? If you squint the right way you could perhaps say that they are, but in general that tends to mean someone who actually holds office.

**Comment by martinszy** [comment]
@tmtmtmtm for my a politician is any person who is playing politics, even if they fail.
Do you have a better name for this model?

**Comment by tmtmtmtm** [comment]
If you're making it that broad, then 'Person'?

**Comment by martinszy** [comment]
Ok, it can be Person if you see it's more fitting.

**Comment by tmtmtmtm** [comment]
I think 'Person' would be more fitting than 'Politician' _if_ the software were to be much more abstract. But I'm far from convinced that that's a sensible thing to do generally.

**Comment by martinszy** [comment]
Moving this issue to the Conocimiento Abierto fork.
