### ISSUE TITLE
Allow for flexibility in older elections and nominations

### ISSUE THREAD

**Issue by martinszy** [mysociety/yournextrepresentative#703]
A candidate can participate in older elections if the elections are created in the site so we know when they were candidates and weather they won that election.
Same for nominations, a candidate can have a nomination that has already ended.

Part of #697 and related to #663

**Comment by tmtmtmtm** [comment]
What prevents this from being possible already?

**Comment by martinszy** [comment]
- Can the users add previous elections at their discretion?
- Nominations don't currently exist, so we may leave this open until it's proven that a politician can have older nominations.

**Comment by martinszy** [comment]
Moving this issue to the Conocimiento Abierto fork.
