### ISSUE TITLE
[CR] Remove ability for general public to edit TusRepresentantesLocales

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/yournextrepresentative#709]
The election is now over and Manfred would like the ability to edit the site to be closed from the public. He'd still like anyone with administrator access to be able to edit the site as they're still marking regidores as won right now.

**Comment by mhl** [comment]
Could you get Manfred to tell us the usernames of users that he would still like to be able to edit? I'll make them staff users, and then set EDITS_ALLOWED to False. (staff users are able to edit even with that setting.)

**Comment by JenMysoc** [comment]
It sounds as though they want to pause this request for the moment as per his email.

**Comment by JenMysoc** [comment]
We've had no further comment on this and the partner is silent so I am closing this for now and will open a new ticket if we reengage and find out this is needed.
