### ISSUE TITLE
Missing Women's Equality Party in Party in 2016 Welsh Assembly Election (Regions):

### ISSUE THREAD

**Issue by brennanpincardiff** [mysociety/yournextrepresentative#722]
Please can you add the Women's Equality Part as a party for the 2016 Welsh Assembly Election. 
I would like to add a candidate for South Wales Central
https://womensequality.nationbuilder.com/ruthwilliams

**Comment by tfgg** [comment]
The party appears to be registered

http://search.electoralcommission.org.uk/English/Registrations/PP2755

We've probably just not done an update of the party lists yet.

**Comment by symroe** [comment]
As @tfgg says, this was because we'd not imported the latest data.  This is fixed now.
