### ISSUE TITLE
"Elected"/"Not elected" on profile pages

### ISSUE THREAD

**Issue by tfgg** [mysociety/yournextrepresentative#729]
On

https://candidates.democracyclub.org.uk/person/7455/sadiq-khan
https://candidates.democracyclub.org.uk/person/7457/peter-whittle

it shows their result for the 2015 UK GE. Obviously this is now misleading. It's not totally obvious what result should be shown, though.

**Comment by symroe** [comment]
The fix in #732 has ben deployed now, so the links above no longer show the bug
