### ISSUE TITLE
Making bulk entry from spreadsheets easier

### ISSUE THREAD

**Issue by tfgg** [mysociety/yournextrepresentative#737]
I've started entering some data from the PCC spreadsheet from the police foundation. I don't think it's worth writing a scraper for these spreadsheets, they're a bit messy and the data needs checking anyway. A rapid manual entry system would be most flexible. Currently bulk adding, say, 5 candidates is a bit fiddly and involving lots of clicking and back-and-forthing. I don't really want to add much more than the person's name and a source, since the spreadsheets rarely have more anyway. Talking with Sym, we thought this sort of workflow might be good:

- 'Bulk add' type button
- Fieldset of 5 or so blank entry rows
- Each row just has Name, Party, Source
- Clicking save creates all of these candidates and returns to the election/post page

Possibly complexity if you also include searching for existing candidates - which I've found is quite important if you don't want to spend a while merging candidates after :)

Does this make sense? I think making the workflow easy for new users to add people starting at the front page is good, but bulk adding would make superuser's lives easier.

**Comment by symroe** [comment]
Calling this done, as per https://github.com/DemocracyClub/yournextrepresentative/commit/d5144cfdcf8c55d0cf9ef18c33d82aeb31c1a28a

**Comment by JoeMitchell** [comment]
More of this please! How many rows can we have before it gets unruly? I could have used 40 or so for North East Scotland list. 

Also it'd be great if it automatically attributed a list number based on the order I added them, is that possible? Or a bulk add field for the regions could be 'number in list'.
