### ISSUE TITLE
UK: Ask for candidate name, not user postcode, on homepage

### ISSUE THREAD

**Issue by zarino** [mysociety/yournextrepresentative#738]
This is a souped-up equivalent to the recently introduced candidate search box, where:
- The search box _replaces_ the postcode input on the homepage
- Typing in the box results in a list of matching candidates (if there are any) which can be clicked to visit their profile, and a prominent "Add a new candidate called XXXX" option (where XXXX is whatever you've typed into the search box).

I have a feeling the search behaviour won't feel natural unless there's immediate feedback in the form of a dropdown autocomplete list (a bit like the country search box on http://everypolitician.org) … but we could at least do a first iteration with just a tweaked version of the existing candidate name search results page, and then progressively enhance to a javascript autocomplete later.

**Comment by zarino** [comment]
I’ve started on this in branch [738-create-from-search-page](https://github.com/mysociety/yournextrepresentative/tree/738-create-from-search-page)

**Comment by jf1** [comment]
I was considering this over the weekend and think a combined search function would be more intuitive for users, and should be simple to implement - if the search term matches a uk postcode then redirect the user to that location, else search for the term in the candidates database.

Auto-complete could still be incorporated but perhaps only after the third character has been input, and only completing candidate names.

**Comment by mhl** [comment]
This is now what happens when you enter a person's name into the search box on https://candidates.democracyclub.org.uk, so I'm closing this ticket now.
