### ISSUE TITLE
UK: Make it possible to create a new candidate without coming via an area page first

### ISSUE THREAD

**Issue by zarino** [mysociety/yournextrepresentative#739]
If we're going to enable people to create a new candidate from the homepage / search page (https://github.com/mysociety/yournextrepresentative/issues/738) we'll need to make sure that there is a stand-alone "create a candidate" page, that lets you pick the candidate’s election and post/area from a list of options, somehow.

We could either present the election and post/area as two successive `<select>`s on the same form page, or we could ask for the election first on its own page, and then use that information to simply forward people on to the already-existing per election new candidate pages (might be quicker to code up in the short term!)

It's important that, once the user finally gets to a form with a "Name:" input field, that field is pre-populated with the text they typed into the search box to begin with (if they came via a homepage search).

**Comment by mhl** [comment]
Although it could definitely do with a lot of work, this does exist now: https://candidates.democracyclub.org.uk/person/create/select_election?name=Joe%20Bloggs
