### ISSUE TITLE
Google login not working on candidates.democracyclub.org.uk

### ISSUE THREAD

**Issue by sjorford** [mysociety/yournextrepresentative#742]
This looks like a different issue to #217.

If I try and log in at https://candidates.democracyclub.org.uk/accounts/login/ using Google, I get:

Error: redirect_uri_mismatch
Application: YourNextMP
The redirect URI in the request: http://candidates.democracyclub.org.uk/accounts/google/login/callback/ did not match a registered redirect URI.

**Comment by mhl** [comment]
This immediate error is now fixed - the allowed redirect URIs for the login were still for edit.yournextmp.com. Another error arose, though, which there's a pull request for here:

https://github.com/mysociety/yournextrepresentative/pull/752

**Comment by mhl** [comment]
That fix has been deployed now, thanks for reporting it, @sjorford
