### ISSUE TITLE
UK: is_secure is always returning False

### ISSUE THREAD

**Issue by mhl** [mysociety/yournextrepresentative#755]
I mentioned this in Slack, but worth recording here too. The DemocracyClub installation of YNR looks as if `request.is_secure` is always returning False regardless of whether the page view was over TLS or not. This has some unfortunately consequences, most obviously that code that generates full URLs to the site (e.g. for use in emails) are using `http` rather than `https`.

Two things need to be done to fix this:

* Make sure `NGINX_SSL` is set to `True` in `general.yml`
* Add `proxy_set_header X-Forwarded-Proto https;` to the nginx locations that are proxying to `http://gunicorn_ynr`.

**Comment by symroe** [comment]
Thanks Mark, I've just done both of these things on the production server.
