### ISSUE TITLE
Navigation out of local elections unobvious

### ISSUE THREAD

**Issue by tfgg** [mysociety/yournextrepresentative#756]
On a page such as

https://candidates.democracyclub.org.uk/election/local.cambridge.2016-05-05/post/DIW:E05002711/petersfield-ward

![image](https://cloud.githubusercontent.com/assets/103349/14051770/3f27b47a-f2bd-11e5-943e-3416e551ce8e.png)

There's no link to an overview of that election, so I can see all the wards/candidates running.

**Comment by symroe** [comment]
Something like this?

![screenshot 2016-03-29 19 37 54](https://cloud.githubusercontent.com/assets/242329/14119374/c5713b48-f5e5-11e5-8d27-72e5ec8949f8.png)

Going to: 

![screenshot 2016-03-29 19 38 30](https://cloud.githubusercontent.com/assets/242329/14119388/d5746a10-f5e5-11e5-8cc8-e4577254a183.png)

**Comment by tfgg** [comment]
Yup, that'd be good.

Maybe also link from under the name on profiles?

![image](https://cloud.githubusercontent.com/assets/103349/14119460/295e4de4-f5e6-11e5-8da2-578da206786a.png)

**Comment by jf1** [comment]
I think Tim's suggestion is more intuitive - but having that link where Sym suggests could help, so how about:
![image](https://cloud.githubusercontent.com/assets/4711363/14119806/d836685a-f5e7-11e5-8abd-5ed62ae735f7.png)


Also, to save clicking on each ward, could Sym's list have eg. " - 2 known candidates" appended to each ward's link?

**Comment by symroe** [comment]
Thanks @jf1, committed in https://github.com/DemocracyClub/yournextrepresentative/commit/4119d695ea5f856b6e0272eea858c70cada5cccf and deployed

**Comment by symroe** [comment]
Leaving this open, as it could be merged back into mySociety master in the future – I expect this applies to other installs too

**Comment by mhl** [comment]
(Duplicating the whole template into the UK-specific templates for a small change like this (rather than a block that could be overridden) seems surprising to me?)

Anyway, yes, I think this will be useful for every country - thank-you! I've taken your change (preserving authorship) and turned it into this PR, with another couple of small related changes:

https://github.com/mysociety/yournextrepresentative/pull/761
