### ISSUE TITLE
“Attention needed” page includes posts from past elections

### ISSUE THREAD

**Issue by andylolz** [mysociety/yournextrepresentative#757]
https://candidates.democracyclub.org.uk/numbers/attention-needed
![screen shot 2016-03-29 at 15 40 25](https://cloud.githubusercontent.com/assets/464193/14111924/a171efa6-f5c4-11e5-832e-1940a681a4e6.png)
These posts do not need attention.

**Comment by jf1** [comment]
Hard to know if this should be two separate issues or just one - please split if you think apt.

There are several places on the site where it'd be more apt to auto-hide old information - I noticed this first in search results, eg: https://candidates.democracyclub.org.uk/search?q=chris
It'd be better to by default only show people confirmed to be involved in May 2016 elections, ideally with a checkbox option in case users wish to 'show pre-2016 information' too.

**Comment by tfgg** [comment]
Hrm. I find it quite useful to show old candidates without having to click another checkbox, since my primary use case of search is looking for old candidate quickly. Perhaps each entry should show the most recent election they were a candidate in?

**Comment by andylolz** [comment]
Looks like Mark has already proposed a fix for this one, so worth creating a new issue for that, @jf1.
