### ISSUE TITLE
alert if any ImageExtra objects disappear

### ISSUE THREAD

**Issue by mhl** [mysociety/yournextrepresentative#767]
I've spent much of the day trying to work out how, at some point after 2016-03-07T16:21:05 all the ImageExtra objects in the Democracy Club database were removed. We're still not sure how this happened, but in case it does again, I suggest we have a cron job set up so that we notice as soon as it does.  I think this should send an email if any are missing:

```
MAILTO=yournextmp@mysociety.org
*/15 * * * * echo 'select i.id from images_image i left outer join candidates_imageextra ie on ie.base_id = i.id where ie.id IS NULL order by i.id;' | psql -q -t ynr | sed '/^$/d'
```

Cc: @symroe

**Comment by symroe** [comment]
This is now running on the server.
