### ISSUE TITLE
When logged in, all candidates marked as elected

### ISSUE THREAD

**Issue by andylolz** [mysociety/yournextrepresentative#772]
![screen shot 2016-04-01 at 00 37 59](https://cloud.githubusercontent.com/assets/464193/14194039/131b9916-f7a2-11e5-9191-e7517f0e61eb.png)

I don’t see “Unset the current winners, if incorrect” for all posts (just some) so that’s possibly a separate bug?

**Comment by mhl** [comment]
I can see how that's confusing, but that's a button you can press to indicate that the candidate was elected after the election is over, not an indication that they were elected. You're seeing those buttons because you're in the "Result Recorders" group.

If you don't see "Unset the current winners, if incorrect" button on some posts, then that is a separate bug, yeah.

**Comment by andylolz** [comment]
> but that's a button you can press to indicate that the candidate was elected after the election is over, not an indication that they were elected

Aha! I knew this (I even remembered it recently) and forgot! Yes, I think it must be confusing, then. Meh.

I basically don’t want to be able to see these buttons until I absolutely need to, because I will inevitably click on one in error. I’ve therefore removed myself from that group!

**Comment by mhl** [comment]
> I basically don’t want to be able to see these buttons until I absolutely need to, because I will inevitably click on one in error. I’ve therefore removed myself from that group!

This is a good point - there's no point in showing these buttons until the current date is >= the election date. Them cluttering up the page annoys me too. Could you create an issue for that?

> > If you don't see "Unset the current winners, if incorrect" button on some posts, then that is a separate bug, yeah.
> 
> Shouldn’t that be the other way around? I only expected to see this button when a winner has been set (which for current elections should be never).

Sorry, you're right - I was getting confused. The "Unset the current winners, if incorrect" button should only be shown if `show_retract_results` is truthy in the context, so if that button is appearing for you for the May 2016 elections, that's a bug.

**Comment by andylolz** [comment]
> This is a good point - there's no point in showing these buttons until the current date is >= the election date. Them cluttering up the page annoys me too. Could you create an issue for that?

Kk done – see #779.
