### ISSUE TITLE
Put party as organisation on popit candidacy memberships?

### ISSUE THREAD

**Issue by tfgg** [mysociety/yournextrepresentative#78]
Currently candidacy memberships don't have a party associated with them and you instead have to iterate through other memberships and match them by the timespan. I was discussing with @mhl whether it made sense in the Popolo format for the organization on the candidacy membership to be set to the party.

**Comment by jpmckinney** [comment]
A discussion started recently about this on the [Poplus](https://groups.google.com/forum/#!forum/poplus) list (unfortunately it's threaded under "Introductions" despite the change in subject). The main issue is this one: https://github.com/popolo-project/popolo-spec/issues/90

The emerging consensus is to use Membership's `onBehalfOf` property to refer to the party.

**Comment by mhl** [comment]
I'm closing this as it's superseded by https://github.com/mysociety/yournextrepresentative/issues/502 - we'll do this migration to using `on_behalf_of` after the PopIt -> django-popolo migration.
