### ISSUE TITLE
Improve name search (to not get confused by middle names)

### ISSUE THREAD

**Issue by JoeMitchell** [mysociety/yournextrepresentative#787]
I just duplicated a load of candidates because I used their middle names, and the search in 'Bulk add candidates' didn't spot them. Gah. 

![image](https://cloud.githubusercontent.com/assets/8096305/14261711/da415968-faa9-11e5-9b31-c6e4432c2ec3.png)

**Comment by JoeMitchell** [comment]
Feedback from a user:

>I recognised one of the candidates (Andrew O'Brien), as I remembered adding him last year for an election in the same area. But when I reviewed the list on candidates - I was *not* prompted to re-use an existing candidate. It appears that your search function didn't find him - maybe it has a problem with apostrophes in names ?

**Comment by jf1** [comment]
In #870 @mhl indicated that there's already a fix available for the apostrophes in names problem.

**Comment by JoeMitchell** [comment]
Ah, so it might have been another problem he was having. Interesting. Ta @jf1 !

**Comment by jf1** [comment]
The fix @mhl highlighted is in MySociety's YNR but I don't know if it has been added to DC by @symroe - it may still need to be applied.

**Comment by mhl** [comment]
Yes, @symroe applied the apostrophe fix to the DC version as e7086637a19fd4 - the middle names issue is a new problem, I think.

**Comment by jf1** [comment]
Some more thoughts on middle and multiple names, and a proposal to standardise them in DC...

Currently DC uses:
Name (shown as "Full name" in the add and edit candidate screens)
Alternative names

These could be:
Primary name - as used on candidate site and promo etc
Formal name - the official name listed on the SoPN (usually includes middle names)
Alternative/AKA - could have multiple AKAs, although I'd hope the above two cover most cases

Examples from [GM Mayor](https://candidates.democracyclub.org.uk/election/mayor.greater-manchester.2017-05-04/post/greater-manchester/greater-manchester) include:
(Fine in DC) Sean Anstee - this is his primary name, his full SoPN name is Sean Brian Anstee
(Weird in DC) Jane Elisabeth Brophy - this is her full/formal name, but she's always known and promoted as Jane Brophy

I expect users would appreciate clear guidance, and that DC's data would benefit from a standardised approach that everyone complies with.
