### ISSUE TITLE
position_in_list looks broken

### ISSUE THREAD

**Issue by andylolz** [mysociety/yournextrepresentative#805]
e.g. 
![screen shot 2016-04-07 at 11 20 25](https://cloud.githubusercontent.com/assets/464193/14348186/c16f158c-fcb2-11e5-9c48-559fd3877f39.png)
(from https://candidates.democracyclub.org.uk/areas/SPC-gss:S16000117,SPE-gss:S17000010,WMC-gss:S14000029)

**Comment by wfdd** [comment]
The party list number is provided by the user. It should show underneath the party selection dropdown when editing a candidate.

**Comment by andylolz** [comment]
Oh I seeeeee! Thanks @wfdd. Okay, that does make sense.

**Comment by wfdd** [comment]
We could show an empty box or a box with a question mark in it.

**Comment by jf1** [comment]
Either of an empty box or a box with a question mark in it would make the list look neater. A question mark might encourage people to edit the candidate and add their position, especially if the image had text on mouseover, eg. "We don't know this candidates position in their party's list. If you know this you can add it by editing the candidate"
