### ISSUE TITLE
Party names & auto-complete

### ISSUE THREAD

**Issue by JeniT** [mysociety/yournextrepresentative#815]
When auto-completing a party name, it would help me pick the most appropriate party name quickly if they were listed based on their popularity (ie the occurrence of candidates of that party in the database). Currently, when I type "Labour Party" I have to scroll through "Socialist Labour Party", "The Independent and Progressive Labour Party" and "Democratic Labour Party" before I get to "Labour Party", which is a pain. Ideally just typing "Lab" would give me the Labour Party as the first choice.

**Comment by mhl** [comment]
Yes, this definitely needs to be improved, and it seems like it's rapidly becoming top user priority. There's a ticket already with some discussion here: #750 so I'll close this in favour of that, but thanks for the report - we'll make sure this is sorted one way or the other soon.
