### ISSUE TITLE
Wyre Forest ward changes

### ISSUE THREAD

**Issue by sjorford** [mysociety/yournextrepresentative#816]
The Wyre Forest wards we have don't match the SOPN - it looks like the district was re-warded for last year's elections, but we have the old set of wards.

**Comment by dracos** [comment]
Yes, the boundaries for Wyre Forest were changed in May 2015 – http://www.legislation.gov.uk/uksi/2015/70/contents/made , not sure why they're not the ones on the DC website.

**Comment by jf1** [comment]
cc'ing @symroe - Wyre Forest's [ward names](www.wyreforestdc.gov.uk/media/1842100/Notice-of-Election-District.pdf) and boundaries were changed over a year ago, for the May 2015 election, but for some reason [c.dc has the previous ones](https://candidates.democracyclub.org.uk/election/local.wyre-forest.2016-05-05/constituencies).
![image](https://cloud.githubusercontent.com/assets/4711363/14583658/0b4cb262-0420-11e6-9a68-692bfbe3d04f.png)

**Comment by JoeMitchell** [comment]
Ta, think this is all sorted now.
