### ISSUE TITLE
Month in candidate birth dates undeclined

### ISSUE THREAD

**Issue by wfdd** [mysociety/yournextrepresentative#817]
In most European languages that are not English, when specifying a date, the month is given in the genitive case.  To quote [Unicode](http://unicode.org/reports/tr35/tr35-dates.html):

> Month, day, and quarter names may vary along two axes: the width and the context.
> 
> The context is either format (the default), the form used within a complete date format string (such as "Saturday, November 12", or stand-alone, the form for date elements used independently, such as in calendar headers. The most important distinction between format and stand-alone forms is a grammatical distinction, for languages that require it. For example, many languages require that a month name without an associated day number (i.e. an independent form) be in the basic nominative form, while a month name with an associated day number (as in a complete date format) should be in a different grammatical form: genitive, partitive, etc. ...

This seems impossible to do with Django's `date` filter, which replicates the PHP `date` function, but can be done with PyICU or Babel or anything that might interface with the [Unicode CLDR](http://cldr.unicode.org/).

**Comment by dracos** [comment]
It's not impossible with `date`, there is an "E" instead of "F" option, which appears to use the genitive (at least for Greek) – for January, it outputs Ιανουαρίου rather than Ιανουάριος.

Alternatively, just use numbers ;)

**Comment by wfdd** [comment]
ah, I missed that.  Thanks @dracos.
