### ISSUE TITLE
Area finder styling broken

### ISSUE THREAD

**Issue by wfdd** [mysociety/yournextrepresentative#831]
After #727, this is what the example app's (and all other apps') front page looks like:

![](http://178.62.171.242:8011/screencapture-127-0-0-1-8000-1460654877520.png)

Either the style changes should be factored out into the UK app or the finder mark-up should be brought in line with the UK's (which I think I'd quite prefer).

**Comment by zarino** [comment]
Pull request here: https://github.com/mysociety/yournextrepresentative/pull/834

**Comment by wfdd** [comment]
Thanks @zarino.
