### ISSUE TITLE
vagrant / install script: make sure libjpeg-dev, libpng12-dev etc. (pillow deps) are installed

### ISSUE THREAD

**Issue by mhl** [mysociety/yournextrepresentative#832]
... or you won't be able to upload those image types to your Vagrant install.

**Comment by mhl** [comment]
Actually, libjpeg-dev is already present:

https://github.com/mysociety/yournextrepresentative/blob/2916a7c9c3b3d46b609b35fca7bb53bcbdb68f46/conf/provision.sh

... but libpng12-dev should be added still.

**Comment by wfdd** [comment]
I'm no expert on such things but when I installed Pillow it said it derived PNG support from zlib.  I don't think libpng is used by Pillow.

**Comment by mhl** [comment]
I've confirmed that there's actually no issue with the current Vagrantfile (as far as Pillow goes anyway, it's far from ideal in other ways) as @wfdd suggests, so I'm closing this.
