### ISSUE TITLE
Byfleet and West Byfleet in Woking are listed as different wards

### ISSUE THREAD

**Issue by markcridge** [mysociety/yournextrepresentative#833]
Byfleet and West Byfleet in Woking are listed as different wards, when they are actually a single ward Byfleet and West Byfleet - http://www.woking.gov.uk/council/election/forthcomingelections/spn2016.pdf

**Comment by dracos** [comment]
The data isn't up to date on Democracy Club for any location with boundary changes. The only place I can see the site tells you this currently is e.g. at the bottom of https://candidates.democracyclub.org.uk/areas/DIW-gss:E05007456,NODATA-gss:E07000217,PDG-police:surrey,WMC-gss:E14001047 (though the top still gives the old ward incorrectly). I think it should be telling you at the top of that page, and on https://whocanivotefor.co.uk/elections/KT14%206AA/ and so on.

The new ward can be seen at http://mapit.mysociety.org/area/148395.html

**Comment by JoeMitchell** [comment]
I think this is all sorted now.
