### ISSUE TITLE
Surname, Forename(s) being entered

### ISSUE THREAD

**Issue by jf1** [mysociety/yournextrepresentative#838]
I was working on [this ward](https://candidates.democracyclub.org.uk/election/local.broxbourne.2016-05-05/post/DIW:E05009006/goffs-oak-ward) at the same time as Bari10, and wanted to replace these:
![image](https://cloud.githubusercontent.com/assets/4711363/14567983/b8c33d14-032e-11e6-9544-034b67636f13.png)

They weren't highlighted as potential duplicates (I had the bulk add page open before Bari10 did their update, then they added the candidates, then I completed the bulk add page which created the duplicates).

This is a waste of my and Bari10's efforts, so ideally there'd be a guide or tool-tip to clarifies that DC currently needs data to be entered as: Forename(s) Surname

...and I'll start another issue with ideas to prevent a post being suggested to a user within X minutes of another user receiving the same suggestion or starting the "Add candidates" process.

**Comment by jnicho02** [comment]
perhaps also encourage use of sentence case. The Council Election pdf I was using listed candidates as "BURGESS Frank James Henry" which I could easily have copied in that format.

**Comment by mhl** [comment]
I think we took a good measure to stop this happening with https://github.com/DemocracyClub/yournextrepresentative/pull/151 so I'm going to close this.
