### ISSUE TITLE
Can't edit George Ferguson - candidacy not displaying?

### ISSUE THREAD

**Issue by sjorford** [mysociety/yournextrepresentative#849]
If I try and edit [George Ferguson's page](https://candidates.democracyclub.org.uk/person/7716) (e.g. to add a Wikipedia link), it complains the post is missing from his candidacy:
![Oops!](https://cloud.githubusercontent.com/assets/10633357/14606970/8271bc7c-0577-11e6-9dc8-6a0da31c6452.png)

Nothing is displaying under the Candidacies section:
![Candidacies - edit mode](https://cloud.githubusercontent.com/assets/10633357/14606969/826e1374-0577-11e6-8b3b-e819aad64b60.png)

But it displays fine in read mode:
![Candidacies - read mode](https://cloud.githubusercontent.com/assets/10633357/14606971/8274f0e0-0577-11e6-97c0-3360f4d9a613.png)

He is the only candidate for Bristol First - is there a problem with that party registration?

**Comment by mhl** [comment]
@sjorford This is one of the cases that will be fixed with: https://github.com/DemocracyClub/yournextrepresentative/pull/20

**Comment by mhl** [comment]
@sjorford You should be able to edit George Ferguson again now - could you give that a go, possibly, and close this issue if it works?

**Comment by sjorford** [comment]
Yep, works a treat now - thanks.
