### ISSUE TITLE
Show if a candidate's been elected in person view

### ISSUE THREAD

**Issue by wfdd** [mysociety/yournextrepresentative#856]
Currently, winners are only indicated in the post view.

**Comment by struan** [comment]
I assume the place to do this is next to the list of elections they are standing in.

I would say at the top of the page but this gets complex if they have been elected in multiple elections as you could only show the latest one but then there are cases like Boris Johnson who has concurrent terms as an MP and London Mayor.

**Comment by wfdd** [comment]
Not any more complex than it is now with showing the latest candidacy under their name, I don't think.  #799 might be of relevance.
