### ISSUE TITLE
Candidate search doesn't work for names with apostrophes

### ISSUE THREAD

**Issue by janetmck** [mysociety/yournextrepresentative#862]
A search from https://candidates.democracyclub.org.uk/search finds nothing for names with apostrophes in, e.g. "O'Brien" (should find e.g. https://candidates.democracyclub.org.uk/person/11568/keith-charles-obrien) and "O'Mara" (should find e.g. https://candidates.democracyclub.org.uk/person/19405/margi-omara).

This also applies to the automated search for duplicates when reviewing newly entered candidates, e.g. re-entering "Margi O'Mara" failed to pick up any possible duplicates. (Given that, when this issue is fixed it would be good to check _all_ names with apostrophes in the DB for possible duplicates!)

**Comment by duncanparkes** [comment]
Has this been deployed on candidates.democraclub yet? I just tried searching for "Mark O'Connor" and couldn't find him.

**Comment by mhl** [comment]
@duncanparkes It isn't in DC's master branch yet.
