### ISSUE TITLE
Post needed in Castle Point St George's ward by-election

### ISSUE THREAD

**Issue by jf1** [mysociety/yournextrepresentative#883]
The standard election [St George's ward in Castle Point](https://candidates.democracyclub.org.uk/election/local.castle-point.2016-05-05/post/DIW:E05004091/st-georges-ward) is fine but there's [no post for the by-election](https://candidates.democracyclub.org.uk/election/local.castle-point.st-georges.2016-05-05/constituencies).

Both elections have an SoPN [here](https://www.castlepoint.gov.uk/elections) and for info [this c.dc link](https://candidates.democracyclub.org.uk/election/local.castle-point.st-georges.2016-05-05/constituencies/unlocked) gives a 500 error.

E05004091

**Comment by jf1** [comment]
Another post needed for:
Member of Parliament
Sheffield by-election: Sheffield Brightside and Hillsborough constituency

**Comment by mhl** [comment]
(The 500 error is a divide-by-zero error because total_constituencies is 0.)

**Comment by jf1** [comment]
Another missing post is Halton ward in Bradford https://candidates.democracyclub.org.uk/election/local.bradford.2016-05-05/constituencies as confirmed in https://www.bradford.gov.uk/bmdc/government_politics_and_public_administration/democracy_and_elections/statement_of_persons_nominated_local_elections

**Comment by JoeMitchell** [comment]
On the case.

**Comment by jf1** [comment]
All 3 now sorted.
