### ISSUE TITLE
Remove 2016 NIA election candidacy from Mark Durkan

### ISSUE THREAD

**Issue by duncanparkes** [mysociety/yournextrepresentative#888]
I erroneously merged Mark Durkan and Mark H Durkan (his nephew). I've created a new Mark H Durkan, but I get a 500 if I try to remove the 2016 National Assembly election from Mark Durkan (https://candidates.democracyclub.org.uk/person/2137).

Can you tidy the data up for me?

**Comment by mhl** [comment]
Once https://github.com/DemocracyClub/yournextrepresentative/pull/28 is merged you should be able to update that candidate's profile again.

**Comment by mhl** [comment]
Done now
