### ISSUE TITLE
the all candidates CSV file should include a line per election

### ISSUE THREAD

**Issue by mhl** [mysociety/yournextrepresentative#891]
At the moment the "all candidates" CSV file generated by `candidates_create_csv` doesn't work well when candidates can stand in multiple elections. If a candidate is standing in multiple elections they should really have multiple rows - much of the data will be the same in each row, but there are candidacy-specific fields.

**Comment by jf1** [comment]
+1. Meant to mention this last week after checking: Sian Berry only appears once but is standing in two elections.
