### ISSUE TITLE
generate CSV files just with results of current elections

### ISSUE THREAD

**Issue by mhl** [mysociety/yournextrepresentative#911]
This is key to make it easy to populate EveryPolitician with data from YNR.

**Comment by wfdd** [comment]
[Oh my god you guys, the bot is sentient!]

**Comment by jf1** [comment]
The DC site has this text:
All Elected Candidates
This CSV file contains details of all candidates in the database who were elected at an election that this site covers.
Download data about all of the candidates

Which isn't entirely accurate. How about:
All Elected Candidates
This CSV file contains details of all candidates in the database who **have been recorded as** elected at an election that this site covers.
Download data about all of the **elected** candidates

**Comment by jf1** [comment]
I was going to suggest, so the list didn't get too long in years/decades to come:
Should this only include current elections, or at least include winners only for as long as their term is still current?

However there's more to it, as 5 unsuccessful London Mayoral candidates were successful in other elections that dc has covered, so they have elected=TRUE for the other election and are being included in [this csv](https://candidates.democracyclub.org.uk/media/candidates-elected-mayor.london.2016-05-05.csv).

**Comment by mhl** [comment]
> However there's more to it, as 5 unsuccessful London Mayoral candidates were successful in other elections that dc has covered, so they have elected=TRUE for the other election and are being included in [this csv](https://candidates.democracyclub.org.uk/media/candidates-elected-mayor.london.2016-05-05.csv).

Damn, that's a bug that was introduced in a late-stage refactoring. A fix is on the way...

**Comment by mhl** [comment]
Fixed in 35f5b315ec5445e6f9f8d6f
