### ISSUE TITLE
2 candidates marked as elected in 3 candidate ward

### ISSUE THREAD

**Issue by duncanparkes** [mysociety/yournextrepresentative#913]
In Peartree ward in Welwyn Hatfield, there should be three people elected, but only two have been marked as such (https://candidates.democracyclub.org.uk/uk_results/posts/DIW:E05004862/)

![2016-05-09-234418_1366x768_scrot](https://cloud.githubusercontent.com/assets/56265/15130498/b3f2a05c-1640-11e6-82bb-ee938565eb39.png)

I wonder if this is because candidates 2 and 3 on the list have the same number of votes.

**Comment by symroe** [comment]
Thanks – this is now fixed and was as you said, because they had the same number of votes (a silly mistake).  aa9f52bdd01f42bb036ff8bcf85f2340e34b9611 fixed it.

**Comment by symroe** [comment]
I've also manually marked Steve Roberts as having won
