### ISSUE TITLE
/help/api text isn't clear/accurate.

### ISSUE THREAD

**Issue by jf1** [mysociety/yournextrepresentative#922]
The DC site has this text:
All Elected Candidates
This CSV file contains details of all candidates in the database who were elected at an election that this site covers.
Download data about all of the candidates

Which isn't entirely accurate. How about:
All Elected Candidates
This CSV file contains details of all candidates in the database who **have been recorded as** elected at an election that this site covers.
Download data about all of the **elected** candidates

Also, the section below's header is:
Current Elections

Which isn't clear, so how about:
Elected Candidates from Current Elections

**Comment by mhl** [comment]
Right, that all sounds better, thanks - I've used those suggestions in b1c52ecad6a492
