### ISSUE TITLE
Limit candidates-elected-all.csv to current elections or terms

### ISSUE THREAD

**Issue by jf1** [mysociety/yournextrepresentative#923]
To ensure [the full list of election winners](https://candidates.democracyclub.org.uk/media/candidates-elected-all.csv) doesn't get too long in years/decades to come: could it only include winners of current elections, or at least only include winners for as long as their term is still current?

**Comment by mhl** [comment]
I think it has more value being complete, and I don't think there's any problem if it continues to grow at the current rate. (Spreadsheet users can always order or filter rows by `election_date` and `election_current`.)
