### ISSUE TITLE
create a settings table for site-specific configuration in the database

### ISSUE THREAD

**Issue by mhl** [mysociety/yournextrepresentative#943]
In order to make it easier to configure a new YourNextRepresentative instance without having to edit files, we'd like to move some of the settings in `conf/general.yml` into a new settings table.

For example, we would want this to include these settings:

* The country that this site is for
* The default language and timezone
* `DATE_FORMAT`
* `SUPPORT_EMAIL`
* `GOOGLE_ANALYTICS_ACCOUNT`
* `TWITTER_USERNAME`
* `RESTRICT_RENAMES`
* `NEW_ACCOUNTS_ALLOWED`
* `EDITS_ALLOWED`
* `HOIST_ELECTED_CANDIDATES`
* `DD_MM_DATE_FORMAT_PREFERRED` *

... and possibly others.

* https://github.com/mysociety/yournextrepresentative/pull/918 would remove this setting anyway

Some questions to address here:

* Should these settings be related to a Site from the sites framework via a foreign key? (Probably.)
* Is there any point in using an existing app to manage this? (Probably not.)

**Comment by struan** [comment]
Having had a bit of a look at existing apps this looks to be the best of them:

https://django-usersettings2.readthedocs.io/en/latest/readme.html

in that it uses the sites framework and has some handy caching and middleware features. It also is the only one I found that supported Python 3. We would need to build an interface on top of it (it does have an admin interface built in)

**Comment by wfdd** [comment]
I'm trying this out right now.  A couple of observations/suggestions:

* I don't think there's a actually 'Date Format' setting.
* Members of the 'Can Edit Settings' user group should be shown a link to the `/settings` page, perhaps next to the mod queue counter.
* In `/settings`, the hoist candidates checkbox's label is not clickable; `<label id="id_HOIST_ELECTED_CANDIDATES">` should be `<label for="id_HOIST_ELECTED_CANDIDATES">`.

**Comment by wfdd** [comment]
I don't think 'Maximum party list size to display on post page' is the right label for `CANDIDATES_REQUIRED_FOR_WEIGHTED_PARTY_LIST` - you might've confused it with the 'default party list members to show' election setting.
