### ISSUE TITLE
Error compiling CSS package "all"

### ISSUE THREAD

**Issue by robertritz** [mysociety/yournextrepresentative#949]
I ran through the deployment wiki and everything is working fine so far. After starting the Django server I loaded the server via IP and received the Error compiling CSS package "all" below. It is displayed at the top of every page I load. At first I thought it might be a mistyped directory or something but previous elections from the repo have these same import commands listed in their style.scss. Can anyone guide me on what's going on here? I'm not familiar with sassc and how it all works.

If I need to manually make the stylesheet thats fine but it seems there are multiple stylesheets around the application. 

```
Error compiling CSS package "all"

Command:

sassc /html/songolt/static/candidates/style.scss /html/songolt/static/candidates/style.css
Errors:

sassc: error: Error: File to import not found or unreadable: ../foundation/scss/foundation/functions
       Parent style sheet: /html/songolt/static/candidates/style.scss
        on line 1 of style.scss
>> @import "../foundation/scss/foundation/functions";
```

**Comment by wfdd** [comment]
It looks like you might've not installed Foundation, a CSS dependency.  In the command line do `git submodule update --init`.

**Comment by robertritz** [comment]
Worked like a charm! Thanks a bunch!
