### ISSUE TITLE
Update repo link

### ISSUE THREAD

**Issue by hugovk** [mysociety/yournextrepresentative#977]
The link at the top -- https://edit.yournextmp.com -- redirects to https://candidates.democracyclub.org.uk

![image](https://cloud.githubusercontent.com/assets/1324225/25404335/304cdea2-2a08-11e7-9df5-bd8d04434c6b.png)

How about updating the link on the repo to https://candidates.democracyclub.org.uk?

**Comment by mhl** [comment]
Thanks, I've done that now. (I did it on DemocracyClub/yournextrepresentative, but forgot the old link was on upstream too.)
