### ISSUE TITLE
Bulk add candidates: ability to see/add/amend Additional Name(s) inline

### ISSUE THREAD

**Issue by jf1** [mysociety/yournextrepresentative#983]
Re. #840 the ability to see/add/amend Additional Name(s) **inline** was suggested by @symroe on Slack:
> On bulk adding: AJAX editing of person names. It takes a long time if an alternative name on the SOPN needs adding because you have to go in to each candidate. This breaks the SOPN flow. Something that lets people edit names inline would be really handy

nb. The need to consider cases where candidates have existing Alternative Name(s).

It'd also be helpful if DC had a policy for preferred names - I suggest we should encourage:
`Name` = `Firstname Lastname` unless they're publicly known as something else, then:
`Alternative Name` = `Firstname Middle-name(s) Lastname` (ie formal name as printed on the SoPN).

I put an example in 787 (but don't want to link there is case there's other irrelevant stuff in that issue):
Examples from [GM Mayor](https://candidates.democracyclub.org.uk/election/mayor.greater-manchester.2017-05-04/post/greater-manchester/greater-manchester) include:
(Fine in DC) Sean Anstee - this is how people know him; his full SoPN name is Sean Brian Anstee.
(Weird in DC) Jane Elisabeth Brophy - this is her full/formal name, but she's always known and promoted as Jane Brophy

**Comment by symroe** [comment]
This would speed up the adding of candidates at the end of this week, so I think this is a good contender for work this week.

**Comment by mhl** [comment]
To add an example to this, on a page like: `/election/nia.2017-03-02/post/osni_oid:NIE-18/foyle`:

![alternative-name-adding](https://cloud.githubusercontent.com/assets/7907/25802133/de754520-33e8-11e7-9df2-f9779beb0672.png)

The existing candidates listed there just have an edit button beside them, and going through that "Edit" to add the variant of the name which is on the ballot paper (which often have more middle names, etc.) is badly distrupting the flow of adding data from nomination papers.

Perhaps the simplest way to deal with this would be to:
* list under each existing candidate name any existing alternative names they have and
* adding a button to add an alternative name, which when clicked unhides an entry box for and additional name
* that box can submit the addition of the alternate name but posting to the existing `PersonOtherNameCreateView`

**Comment by zarino** [comment]
We’ve started this in branch [DemocracyClub:bulk-edit-alt-name-editing](https://github.com/DemocracyClub/yournextrepresentative/compare/master...DemocracyClub:bulk-edit-alt-name-editing?expand=1)

**Comment by struan** [comment]
Fixed in https://github.com/DemocracyClub/yournextrepresentative/commit/cd5a7187bcbe36de2a3aa5feedc976bdf9efe956
