### ISSUE TITLE
Kenya: add a new Django app for kenya

### ISSUE THREAD

**Issue by mhl** [mysociety/yournextrepresentative#985]
It seems likely that we'll set up a candidates site for the 2017 Kenyan elections. Although we don't have candidate data yet, and it's not clear what form it'll come in (e.g. an API like last time, or a CSV file) we can at least add an `elections/kenya` Django application, and change the colour scheme of the site to match Mzalendo. (This can be largely done by setting Sass variables, so shouldn't take a long time.)

**Comment by chrismytton** [comment]
This was done in https://github.com/mysociety/yournextrepresentative/commit/f564eb3e59bfcb8fe517fe7eac8e6c3ec2296ff0 :tada:
