### ISSUE TITLE
Kenya: 500 error when trying to view Jacklyne Nekesa Nyongesa

### ISSUE THREAD

**Issue by chrismytton** [mysociety/yournextrepresentative#992]
I'm getting a 500 error when I try to visit the page for Jacklyne Nekesa Nyongesa:

http://kenya.ynr.mysociety.org/person/499/jacklyne-nekesa-nyongesa

I _think_ this is because they have multiple party memberships, which is shown by the following command:

    curl -s http://kenya.ynr.mysociety.org/media/candidates-all.csv | grep 'Jacklyne Nekesa Nyongesa'

However I don't know enough about YNR's data model to dig any deeper, I'm afraid.

**Comment by jacksonj04** [comment]
This is due to a duplicate IEBC identifier, resolved in https://github.com/mysociety/yournextrepresentative/commit/ed7aea74e8bb5c1310bb9f53e7fe93e54b493366.

**Comment by jacksonj04** [comment]
Jacklyne Nekesa Nyongesa is now at http://kenya.ynr.mysociety.org/person/14523/jacklyne-nekesa-nyongesa, and the person at http://kenya.ynr.mysociety.org/person/499/annah-nandako-masibo is now correctly Annah Nandako Masibo.
